In [1]:
import pandas as pd
import numpy as np
import csv
import re
from bs4 import BeautifulSoup
import camelot 

from tabula import read_pdf
from tabulate import tabulate
from itertools import chain
import matplotlib as plt

import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

# %matplotlib inline
%config InlineBackend.figure_format='retina'
# If encounter SSL certify error - go to your Python 3.x.x folder and install Certification

In [2]:
csv = pd.read_csv('farm_smoke.csv')
sonoma_data = csv.query('County == "Sonoma" and Year >= 2001').copy().reset_index(drop=True)
sonoma_data

    County  Year                                              Links
0   Sonoma  2021  https://sonomacounty.ca.gov//Main%20County%20S...
1   Sonoma  2020  https://sonomacounty.ca.gov//Main%20County%20S...
2   Sonoma  2019  https://sonomacounty.ca.gov//Main%20County%20S...
3   Sonoma  2018  https://sonomacounty.ca.gov//Main%20County%20S...
4   Sonoma  2017  https://sonomacounty.ca.gov//Main%20County%20S...
5   Sonoma  2016  https://sonomacounty.ca.gov//Main%20County%20S...
6   Sonoma  2015  https://sonomacounty.ca.gov//Main%20County%20S...
7   Sonoma  2014  https://sonomacounty.ca.gov//Main%20County%20S...
8   Sonoma  2013  https://sonomacounty.ca.gov//Main%20County%20S...
9   Sonoma  2012  https://sonomacounty.ca.gov//Main%20County%20S...
10  Sonoma  2011  https://sonomacounty.ca.gov//Main%20County%20S...
11  Sonoma  2010  https://sonomacounty.ca.gov//Main%20County%20S...
12  Sonoma  2009  https://sonomacounty.ca.gov//Main%20County%20S...
13  Sonoma  2008  https://sonomacounty.ca.gov//Main%20County%20S...
14  Sonoma  2007  https://sonomacounty.ca.gov//Main%20County%20S...
15  Sonoma  2006  https://sonomacounty.ca.gov//Main%20County%20S...
16  Sonoma  2005  https://sonomacounty.ca.gov//Main%20County%20S...
17  Sonoma  2004  https://sonomacounty.ca.gov//Main%20County%20S...
18  Sonoma  2003  https://sonomacounty.ca.gov//Main%20County%20S...
19  Sonoma  2002  https://sonomacounty.ca.gov//Main%20County%20S...
20  Sonoma  2001  https://sonomacounty.ca.gov//Main%20County%20S...

In [3]:
urls = sonoma_data['Links']
urls

0     https://sonomacounty.ca.gov//Main%20County%20S...
1     https://sonomacounty.ca.gov//Main%20County%20S...
2     https://sonomacounty.ca.gov//Main%20County%20S...
3     https://sonomacounty.ca.gov//Main%20County%20S...
4     https://sonomacounty.ca.gov//Main%20County%20S...
5     https://sonomacounty.ca.gov//Main%20County%20S...
6     https://sonomacounty.ca.gov//Main%20County%20S...
7     https://sonomacounty.ca.gov//Main%20County%20S...
8     https://sonomacounty.ca.gov//Main%20County%20S...
9     https://sonomacounty.ca.gov//Main%20County%20S...
10    https://sonomacounty.ca.gov//Main%20County%20S...
11    https://sonomacounty.ca.gov//Main%20County%20S...
12    https://sonomacounty.ca.gov//Main%20County%20S...
13    https://sonomacounty.ca.gov//Main%20County%20S...
14    https://sonomacounty.ca.gov//Main%20County%20S...
15    https://sonomacounty.ca.gov//Main%20County%20S...
16    https://sonomacounty.ca.gov//Main%20County%20S...
17    https://sonomacounty.ca.gov//Main%20County%20S...
18    https://sonomacounty.ca.gov//Main%20County%20S...
19    https://sonomacounty.ca.gov//Main%20County%20S...
20    https://sonomacounty.ca.gov//Main%20County%20S...
Name: Links, dtype: object

In [4]:
# Note 1: 2021 - 2017 can work together 
# Note 2: 2016 - format diff, have -- and ' .' formating, top 12 reds 
# Note 3: 2015, 2014 - top 12 reds
# Note 4: 2013, 2012 - format change, words and style is diff; need to change camelot

table_list = []
for link, year in zip(urls, sonoma_data['Year']):
    page = '12'
    if year == 2017 or year == 2004 or year == 2003 or year == 2001:
        page = '10'
    elif year == 2007:
        page = '9'
    elif year == 2016 or year == 2013 or year == 2011 or year == 2010 or year == 2009:
        page = '8'
    elif year == 2014 or year == 2012 or year == 2006:
        page = '7'
    elif year == 2008 or year == 2005:
        page = '11'
    # utilize camelot to read pdf file at page 12, 
    # capture precisely with stream and close up the row gap with row_tol = 10

    if year <= 2011:
        if year == 2011:
            # specific reads for 2011
            tables = camelot.read_pdf(link, pages=page, table_areas=['30,720,600,250'], flavor='stream', row_tol=8)[0].df
        elif year == 2004:
            tables = camelot.read_pdf(link, pages=page, table_areas=['60,740,600,370'], flavor='stream', row_tol=8,split_text=True)[0].df
        elif year == 2005:
            tables = camelot.read_pdf(link, pages=page, table_areas=['50,720,600,300'], flavor='stream', row_tol=8, split_text=True)[0].df
        elif year <= 2010 and year != 2005 and year != 2004:
            tables = camelot.read_pdf(link, pages=page, flavor='stream', row_tol=8, split_text=True)[0].df
    elif year != 2012 and year != 2013:
        tables = camelot.read_pdf(link, pages=page, flavor='stream', row_tol=10)[0].df
    
    display(tables)
    table_list.append(tables)
print('finish reading pdf files')

,0,1,2,3,4,5,6,7
0,,,TOP 13 BY VALUE - LISTED ALPHABETICALLY,,,,,
1,,,,Acreage,,,Production,
2,Varietal,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
3,Cabernet Franc,2021,552.0,33.0,585.0,"1,150.4","$3,866.85","$4,448,400"
4,,2020,557 0,29 0,586 0,942 4,"$3,534 95","$3,331,300"
5,Cabernet,2021,"12,293.0",429.0,"12,722.0","41,114.6","$2,728.69","$112,189,000"
6,Sauvignon,2020,"12,089 0",631 0,"12,720 0","31,137 9","$2,460 15","$76,603,900"
7,Carignane,2021,156.0,2.0,158.0,280.7,"$2,633.52","$739,200"
8,,2020,158 0,6 0,164 0,257 9,"$2,447 30","$631,200"
9,Grenache,2021,211.0,55.0,266.0,898.4,"$3,101.70","$2,786,600"
10,,2020,203 0,58 0,261 0,751 7,"$2,509 56","$1,886,400"
11,Malbec,2021,422.0,26.0,448.0,"1,577.2","$3,081.97","$4,860,900"
12,,2020,414 0,16 0,430 0,"1,004 8","$2,643 18","$2,655,900"
13,Mataro/,2021,71.0,11.0,82.0,179.1,"$3,176.28","$568,900"
14,Mouvedere,2020,65 0,8 0,73 0,108 3,"$2,874 98","$311,400"
15,Merlot,2021,"4,140.0",17.0,"4,157.0","7,828.5","$1,961.32","$15,354,200"
16,,2020,"4,175 0",17 0,"4,192 0","5,652 8","$1,589 61","$8,985,700"
17,Petite Sirah,2021,651.0,26.0,677.0,"2,163.9","$2,996.48","$6,484,100"
18,,2020,641 0,42 0,683 0,"1,622 1","$2,706 91","$4,390,900"
19,,2021,242.0,6.0,248.0,983.1,"$3,536.74","$3,477,000"
20,Petit Verdot,2020,244 0,7 0,251 0,494 6,"$3,184 33","$1,575,000"
21,Pinot Noir,2021,"12,608.0",265.0,"12,873.0","48,496.5","$3,512.27","$170,332,800"
22,,2020,"12,516 0",497 0,"13,013 0","29,263 7","$3,146 85","$92,088,500"
23,,2021,278.0,4.0,282.0,879.7,"$2,493.41","$2,193,500"
24,Sangiovese,2020,279 0,4 0,283 0,398 9,"$2,364 77","$943,300"
25,Syrah-Shiraz,2021,"1,326.0",34.0,"1,360.0","2,450.6","$2,871.85","$7,037,800"
26,,2020,"1,352 0",29 0,"1,381 0","1,581 5","$2,472 14","$3,909,700"
27,Zinfandel,2021,"4,613.0",116.0,"4,729.0","11,660.0","$3,113.73","$36,306,100"
28,,2020,"4,654 0",105 0,"4,759 0","8,397 0","$2,624 37","$22,036,800"
29,TOTAL ALL REDS,2021,"38,128.0","1,056.0","39,184.0","121,693.0","$3,060.13","$372,396,400"
30,including other reds,2020,"37,916 0","1,493 0","39,409 0","82,910 2","$2,651 92","$219,871,200"

,0,1,2,3,4,5,6,7
0,,,TOP 13 BY VALUE - LISTED ALPHABETICALLY,,,,,
1,,,,Acreage,,,Production,
2,Varietal,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
3,Cabernet Franc,2020,557.0,29.0,586.0,942.4,"$3,534.95","$3,331,300"
4,,2019,562.0,13.0,575.0,"1,533.4","$3,815.93","$5,851,300"
5,Cabernet,2020,"12,089.0",631.0,"12,720.0","31,137.9","$2,460.15","$76,603,900"
6,Sauvignon,2019,"12,082.0",539.0,"12,621.0","45,948.3","$3,055.93","$140,414,800"
7,Carignane,2020,158.0,6.0,164.0,257.9,"$2,447.30","$631,200"
8,,2019,170.0,6.0,176.0,416.5,"$2,591.56","$1,079,400"
9,Grenache,2020,203.0,58.0,261.0,751.7,"$2,509.56","$1,886,400"
10,,2019,183.0,43.0,226.0,806.1,"$3,203.49","$2,582,300"
11,Malbec,2020,414.0,16.0,430.0,"1,004.8","$2,643.18","$2,655,900"
12,,2019,416.0,22.0,438.0,"1,863.0","$3,041.79","$5,666,900"
13,Mataro/,2020,65.0,8.0,73.0,108.3,"$2,874.98","$311,400"
14,Mouvedere,2019,63.0,10.0,73.0,182.8,"$3,455.43","$631,700"
15,Merlot,2020,"4,175.0",17.0,"4,192.0","5,652.8","$1,589.61","$8,985,700"
16,,2019,"4,346.0",47.0,"4,393.0","12,312.3","$2,000.15","$24,626,400"
17,Petite Sirah,2020,641.0,42.0,683.0,"1,622.1","$2,706.91","$4,390,900"
18,,2019,635.0,21.0,656.0,"2,628.3","$3,154.98","$8,300,000"
19,Petit Verdot,2020,244.0,7.0,251.0,494.6,"$3,184.33","$1,575,000"
20,,2019,249.0,4.0,253.0,"1,025.0","$3,403.84","$3,500,000"
21,Pinot Noir,2020,"12,516.0",497.0,"13,013.0","29,263.7","$3,146.85","$92,088,500"
22,,2019,"12,509.0",585.0,"13,094.0","47,178.3","$3,949.20","$186,316,500"
23,Sangiovese,2020,279.0,4.0,283.0,398.9,"$2,364.77","$943,300"
24,,2019,279.0,1.0,283.0,993.4,"$2,576.02","$2,559,000"
25,Syrah-Shiraz,2020,"1,352.0",29.0,"1,381.0","1,581.5","$2,472.14","$3,909,700"
26,,2019,"1,396.0",12.0,"1,408.0","3,334.3","$2,811.92","$9,400,000"
27,Zinfandel,2020,"4,654.0",105.0,"4,759.0","8,397.0","$2,624.37","$22,036,800"
28,,2019,"4,758.0",50.0,"4,808.0","14,817.7","$3,143.05","$46,572,800"
29,TOTAL ALL REDS,2020,"37,916.0","1,493.0","39,409.0","82,910.2","$2,651.92","$219,871,200"
30,including other reds,2019,"38,212.0","1,404.0","39,616.0","135,051.7","$3,254.92","$439,582,500"

,0,1,2,3,4,5,6,7
0,,,TOP 13 BY VALUE - LISTED ALPHABETICALLY,,,,,
1,,,,Acreage,,,Production,
2,Varietal,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
3,Cabernet Franc,2019,562.0,13.0,575.0,"1,533.4","$3,815.93","$5,851,300"
4,,2018,565.0,10.6,575.6,"1,832.6","$3,567.17","$6,537,200"
5,Cabernet,2019,"12,082.0",539.0,"12,621.0","45,948.3","$3,055.93","$140,414,800"
6,Sauvignon,2018,"12,505.1",642.3,"13,147.4","56,948.2","$3,113.75","$177,322,500"
7,Carignane,2019,170.0,6.0,176.0,416.5,"$2,591.56","$1,079,400"
8,,2018,162.7,9.7,172.4,406.9,"$2,654.55","$1,080,100"
9,Grenache,2019,183.0,43.0,226.0,806.1,"$3,203.49","$2,582,300"
10,,2018,150.2,12.1,162.3,929.0,"$3,025.64","$2,810,800"
11,Malbec,2019,416.0,22.0,438.0,"1,863.0","$3,041.79","$5,666,900"
12,,2018,536.0,9.3,545.3,"2,695.1","$2,894.42","$7,800,800"
13,Mataro/,2019,63.0,10.0,73.0,182.8,"$3,455.43","$631,700"
14,Mouvedere,2018,40.6,0.9,41.5,216.4,"$3,236.82","$700,400"
15,Merlot,2019,"4,346.0",47.0,"4,393.0","12,312.3","$2,000.15","$24,626,400"
16,,2018,"3,940.8",10.2,"3,951.0","15,492.0","$1,961.96","$30,394,700"
17,Petite Sirah,2019,635.0,21.0,656.0,"2,628.3","$3,154.98","$8,300,000"
18,,2018,685.3,2.0,687.3,"2,954.5","$3,088.27","$9,124,300"
19,Petit Verdot,2019,249.0,4.0,253.0,"1,025.0","$3,403.84","$3,500,000"
20,,2018,284.3,18.6,302.9,"1,324.8","$3,336.84","$4,420,600"
21,Pinot Noir,2019,"12,509.0",585.0,"13,094.0","47,178.3","$3,949.20","$186,316,500"
22,,2018,"13,383.6",880.0,"14,263.6","58,005.2","$3,802.05","$220,538,700"
23,Sangiovese,2019,279.0,1.0,280.0,993.4,"$2,576.02","$2,559,000"
24,,2018,211.4,0.0,211.4,"1,070.2","$2,477.26","$2,651,200"
25,Syrah-Shiraz,2019,"1,396.0",12.0,"1,408.0","3,334.3","$2,811.92","$9,400,000"
26,,2018,"1,557.8",3.7,"1,561.5","3,966.9","$2,773.75","$11,003,200"
27,Zinfandel,2019,"4,758.0",50.0,"4,808.0","14,817.7","$3,143.05","$46,572,800"
28,,2018,"4,946.6",24.4,"4,971.0","15,730.6","$3,102.26","$48,800,400"
29,TOTAL ALL REDS,2019,"38,212.0","1,404.0","39,616.0","135,051.7","$3,254.92","$439,582,500"
30,including other reds,2018,"39,842.0","1,956.4","41,798.4","163,575.2","$3,227.84","$527,994,600"

,0,1,2,3,4,5,6,7
0,,,TOP 13 BY VALUE - LISTED ALPHABETICALLY,,,,,
1,,,,Acreage,,,Production,
2,Varietal,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
3,Cabernet Franc,2018,565.0,10.6,575.6,"1,832.6","$3,567.17","$6,537,200"
4,,2017,565.0,35.6,600.6,"1,382.4","$3,335.31","$4,610,700"
5,Cabernet,2018,"12,505.1",642.3,"13,147.4","56,948.2","$3,113.75","$177,322,500"
6,Sauvignon,2017,"12,530.9",530.4,"13,061.3","43,157.9","$3,071.98","$132,580,200"
7,Carignane,2018,162.7,9.7,172.4,406.9,"$2,654.55","$1,080,100"
8,,2017,162.7,0.0,162.7,260.4,"$2,665.76","$694,200"
9,Grenache,2018,150.2,12.1,162.3,929.0,"$3,025.64","$2,810,800"
10,,2017,153.8,8.0,161.8,854.7,"$3,076.99","$2,630,000"
11,Malbec,2018,536.0,9.3,545.3,"2,695.1","$2,894.42","$7,800,800"
12,,2017,536.0,11.3,548.3,"1,700.8","$2,953.95","$5,024,100"
13,Mataro/,2018,40.6,0.9,41.5,216.4,"$3,236.82","$700,400"
14,Mouvedere,2017,41.6,0.9,42.5,158.2,"$2,895.20","$458,000"
15,Merlot,2018,"3,940.8",10.2,"3,951.0","15,492.0","$1,961.96","$30,394,700"
16,,2017,"3,978.8",22.6,"4,001.4","11,611.1","$1,922.95","$22,327,400"
17,Petite Sirah,2018,685.3,2.0,687.3,"2,954.5","$3,088.27","$9,124,300"
18,,2017,688.8,4.2,693.0,"2,536.3","$2,905.75","$7,370,000"
19,Petit Verdot,2018,284.3,18.6,302.9,"1,324.8","$3,336.84","$4,420,600"
20,,2017,284.3,9.9,294.2,915.6,"$3,156.58","$2,890,200"
21,Pinot Noir,2018,"13,383.6",880.0,"14,263.6","58,005.2","$3,802.05","$220,538,700"
22,,2017,"13,414.3",423.8,"13,838.1","43,439.1","$3,912.46","$169,953,700"
23,Sangiovese,2018,211.4,0.0,211.4,"1,070.2","$2,477.26","$2,651,200"
24,,2017,316.5,0.0,316.5,916.8,"$2,400.63","$2,200,900"
25,Syrah-Shiraz,2018,"1,557.8",3.7,"1,561.5","3,966.9","$2,773.75","$11,003,200"
26,,2017,"1,571.7",8.5,"1,580.2","3,216.5","$2,779.67","$8,940,800"
27,Zinfandel,2018,"4,946.6",24.4,"4,971.0","15,730.6","$3,102.26","$48,800,400"
28,,2017,"4,976.9",16.9,"4,993.9","12,874.5","$3,006.42","$38,706,200"
29,TOTAL ALL REDS,2018,"39,842.0","1,956.4","41,798.4","163,575.2","$3,227.84","$527,994,600"
30,including other reds,2017,"39,996.5","1,658.8","41,655.3","124,787.5","$3,219.57","$401,762,100"

,0,1,2,3,4,5,6,7
0,,,,TOP 13 BY VALUE - LISTED ALPHABETICALLY,,,,
1,,,,Acreage,,,Production,
2,Varietal,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
3,Cabernet Franc,2017,565.0,35.6,600.6,"1,382.4","$3,335.31","$4,610,700"
4,,2016,578 5,28 5,607 0,"1,382 5","$2,955 14","$4,085,500"
5,Cabernet,2017,"12,530.9",530.4,"13,061.3","43,157.9","$3,071.98","$132,580,200"
6,Sauvignon,2016,"12,456 7",560 0,"13,016 7","41,575 7","$2,964 60","$123,255,300"
7,,2017,162.7,0.0,162.7,260.4,"$2,665.76","$694,200"
8,Carignane,2016,162 7,0 0,162 7,305 8,"$2,195 62","$671,500"
9,Grenache,2017,153.8,8.0,161.8,854.7,"$3,076.99","$2,630,000"
10,,2016,152 7,3 6,156 3,739 7,"$2,995 16","$2,215,500"
11,Malbec,2017,536.0,11.3,548.3,"1,700.8","$2,953.95","$5,024,100"
12,,2016,551 5,4 7,556 2,"2,960 5","$2,629 78","$7,785,500"
13,Mataro/,2017,41.6,0.9,42.5,158.2,"$2,895.20","$458,000"
14,Mouvedere,2016,41 6,0 9,42 5,771 5,"$2,119 36","$1,635,100"
15,,2017,"3,978.8",22.6,"4,001.4","11,611.1","$1,922.95","$22,327,400"
16,Merlot,2016,"4,115 7",24 6,"4,140 3","13,761 0","$1,818 10","$25,018,900"
17,Petite Sirah,2017,688.8,4.2,693.0,"2,536.3","$2,905.75","$7,370,000"
18,,2016,694 5,4 2,698 7,"3,266 3","$2,797 89","$9,138,700"
19,Petit Verdot,2017,284.3,9.9,294.2,915.6,"$3,156.58","$2,890,200"
20,,2016,278 3,16 5,294 8,"1,332 0","$2,976 71","$3,965,000"
21,Pinot Noir,2017,"13,414.3",423.8,"13,838.1","43,439.1","$3,912.46","$169,953,700"
22,,2016,"13,343 1",385 2,"13,728 3","42,566 3","$3,680 50","$156,665,300"
23,,2017,316.5,0.0,316.6,916.8,"$2,400.63","$2,200,900"
24,Sangiovese,2016,316 9,0 0,316 9,"1,091 1","$2,314 48","$2,525,300"
25,Syrah-Shiraz,2017,"1,571.7",8.5,"1,580.2","3,216.5","$2,779.67","$8,940,800"
26,,2016,"1,575 6",13 5,"1,589 1","3,618 1","$2,596 01","$9,392,600"
27,Zinfandel,2017,"4,976.9",16.9,"4,993.9","12,874.5","$3,006.42","$38,706,200"
28,,2016,"5,070 5",20 0,"5,090 5","15,287 7","$2,840 06","$43,418,000"
29,TOTAL ALL REDS,2017,"39,996.5","1,658.8","41,655.3","124,787.5","$3,219.57","$401,762,100"
30,including other reds,2016,"39,821 4","1,342 0","41,163 5","130,589 3","$3,008 75","$392,910,600"

,0,1,2,3,4,5,6,7
0,,,Acreage,,,,Production,
1,Varietal,Year,Non-Bearing,Bearing,Total,Tons,$/Tons,Total Value
2,,2016,385.2,"13,343.1","13,728.3","42,566.3","$3,680.50","$156,665,300"
3,Pinot Noir,2015,750 .0,"12,850 .8","13,600 .8","30,667 .2","$3,525 .42","$108,114,800"
4,Cabernet,2016,560.0,"12,456.7","13,016.7","41,575.7","$2,964.60","$123,255,300"
5,Sauvignon,2015,"1,014 .7","11,808 .8","12,823 .5","32,947 .3","$2,724 .17","$89,754,100"
6,,2016,20.0,"5,070.5","5,090.5","15,287.7","$2,840.06","$43,418,000"
7,Zinfandel,2015,85 .1,"4,988 .3","5,073 .4","13,070 .9","$2,711 .07","$35,436,200"
8,,2016,24.6,"4,115.7","4,140.3","13,761.0","$1,818.10","$25,018,900"
9,Merlot,2015,43 .4,"4,108 .2","4,151 .6","12,031 .4","$1,717 .25","$20,661,000"
10,,2016,13.5,"1,575.6","1,589.1","3,618.1","$2,596.01","$9,392,600"
11,Syrah - Shiraz,2015,15 .5,"1,569 .8","1,585 .3","2,848 .1","$2,525 .16","$7,192,000"
12,,2016,4.2,694.5,698.7,"3,266.3","$2,797.89","$9,138,700"
13,Petite Sirah,2015,50 .4,645 .6,696 .0,"2,347 .4","$2,715 .79","$6,375,100"
14,,2016,4.7,551.5,556.2,"2,960.5","$2,629.78","$7,785,500"
15,Malbec,2015,12 .9,540 .5,553 .4,"1,896 .3","$2,636 .24","$4,999,200"
16,Cabernet Franc,2016,28.5,578.5,607.0,"1,382.5","$2,955.14","$4,085,500"
17,,2015,34 .3,569 .9,604 .2,"1,357 .8","$2,794 .59","$3,794,400"
18,Petit Verdot,2016,16.5,278.3,294.8,"1,332.0","$2,976.71","$3,965,000"
19,,2015,25 .7,266 .2,291 .9,953 .4,"$2,719 .87","$2,593,200"
20,Sangiovese/,2016,--,316.9,316.9,"1,091.1","$2,314.48","$2,525,300"
21,Sangioveto,2015,--,211 .3,211 .3,929 .3,"$2,244 .27","$2,085,700"
22,Grenache,2016,3.6,152.7,156.3,739.7,"$2,995.16","$2,215,500"
23,,2015,3 .7,146 .4,150 .1,567 .4,"$2,901 .69","$1,646,500"
24,Mataro/,2016,0.9,41.6,42.5,771.5,"$2,119.36","$1,635,100"
25,Mourvedere (a),2015,--,--,--,149 .7,"$3,082 .19","$461,400"
26,TOTAL REDS,2016,"1,342.0","39,821.4","41,163.5","130,589.3","$3,008.75","$392,910,600"
27,including other reds,2015,"2,679 .1","38,917 .8","41,596 .9","101,800 .1","$2,819 .84","$287,060,000"

,0,1,2,3,4,5,6,7
0,,,,Acreage,,,Production,
1,Varietal,Year,Bearing,Non-Bearing,Total,Tons,$/Tons,Total Value
2,,2015,569.9,34.3,604.1,"1,357.8","$2,794.59","$3,794,400"
3,Cabernet Franc,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
4,Cabernet,2015,"11,808.8","1,014.7","12,823.4","32,947.3","$2,724.17","$89,754,100"
5,Sauvignon,2014,11 689.7,"1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
6,,2015,162.7,0.0,162.7,305.8,"$2,195.62","$671,500"
7,Carignane,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
8,,2015,146.4,3.7,150.1,567.4,"$2,901.69","$1,646,500"
9,Grenache,2014,119.3,5.2,124.5,701.7,"$2,830.53","$1,986,200"
10,,2015,540.5,12.9,553.4,"1,896.3","$2,636.24","$4,999,200"
11,Malbec,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
12,,2015,"4,108.2",43.4,"4,151.6","12,031.4","$1,717.25","$20,661,000"
13,Merlot,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"
14,,2015,645.6,50.4,696.0,"2,347.4","$2,715.79","$6,375,100"
15,Petite Sirah,2014,630.1,55.1,685.2,"2,873.5","$2,548.12","$7,332,100"
16,Petite Verdot,2015,266.2,25.7,292.0,953.4,"$2,719.87","$2,593,200"
17,,2014,250.0,34.2,284.2,"1,251.1","$2,667.28","$3,337,100"
18,Pinot Noir,2015,"12,850.8",750.0,"13,600.7","30,667.2","$3,525,42","$108,114,800"
19,,2014,"12,567.9","1,014.4","13,582.7","47,677.2","$3,251.49","$155,022,000"
20,Sangiovese,2015,211.3,0.0,211.3,929.3,"$2,244.27","$2,085,700"
21,,2014,210.2,0.0,210.3,"1,211.9","$2,352.94","$2,851,600"
22,Syrah-Shiraz,2015,"1,569.8",15.5,"1,585.3","2,848.1",$2.525.16,"$7,192,000"
23,,2014,"1,649.5",9.8,"1,659.3","4,642.6","$2,314.44","$10,745,100"
24,Zinfandel,2015,"4,988.3",85.1,"5,073.4","13,070.9","$2,711.07","$35,436,200"
25,,2014,"5,015.8",112.1,"5,127.9","15,597.2","$2,543.78","$39,675,900"
26,TOTAL REDS,2015,"38,917.8","2,679.1","41,596.9","101,800.1","$2,819.84","$287,060,000"
27,Includes other Reds,2014,"38,775.8","3,037.2","41,813.0","144,021.5","$2,685.05","$386,705,000"

,0,1,2,3,4,5,6,7
0,Top 12,,,Acreage,,,Production,
1,Red Varieties,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
2,Cabernet Franc,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
3,,2013,604.5,13.2,617.7,"1,917.8","$2,445.23","$4,689,500"
4,Cabernet Sauvignon,2014,"11,689.7","1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
5,,2013,"11,830.3","1,070.8","12,901.1","44,255.8","$2,462.99","$109,001,600"
6,Carignane,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
7,,2013,579.6,4.0,583.6,506.7,"$1,870.18","$947,700"
8,Malbec,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
9,,2013,425.7,109.4,535.1,"2,706.6","$2,356.19","$6,377,300"
10,Merlot,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"
11,,2013,"4,619.9",27.3,"4,647.2","18,784.5","$1,607.03","$30,187,300"
12,Meunier,2014,88.8,6.6,95.4,607.6,"$2,305.57","$1,400,900"
13,,2013,91.8,6.6,98.4,716.9,"$2,285.40","$1,638,500"
14,Petite Sirah,2014,630.1,55.1,685.2,"2,873.5","$2,548.12","$7,322,100"
15,,2013,598.3,83.5,681.8,"2,856.8","$2,477.06","$7,076,500"
16,Petite Verdot,2014,250.0,34.2,284.2,"1,251.1","$2,667.28","$3,337,100"
17,,2013,236.9,30.5,267.4,"1,120.0","$2,840.39","$3,181,300"
18,Pinot Noir,2014,"12,567.9","1,014.4","13,582.3","47,677.2","$3,251.49","$155,022,000"
19,,2013,"12,539.3",948.1,"13,487.4","54,826.8","$3,079.99","$168,866,000"
20,Sangiovese,2014,210.2,0.0,210.2,"1,211.9","$2,352.94","$2,851,600"
21,,2013,195.9,12.7,208.6,"1,141.1","$2,383.10","$2,719,400"
22,Syrah-Shiraz,2014,"1,649.5",9.8,"1,659.3","4,642.6","$2,314.44","$10,745,100"
23,,2013,"1,731.9",7.0,"1,738.9","4,835.8","$2,246.05","$10,861,500"
24,Zinfandel,2014,"5,015.8",112.1,"5,127.9","15,597.2","$2,543.78","$39,675,900"
25,,2013,"5,139.0",159.8,"5,298.8","20,172.3","$2,444.51","$49,311,400"
26,TOTAL ALL REDS,2014,"38,775.8","3,037.2","41,813.0","144,021.5","$2,685.05","$386,705,000"
27,Includes other reds,2013,"39,788.7","3,167.3","42,956.0","156,435.3","$2,558.50","$400,239,800"

,0,1,2,3,4,5,6,7
0,Top 12,,,Acreage,,,Production,
1,Red Varieties,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
2,Cabernet Franc,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
3,,2013,604.5,13.2,617.7,"1,917.8","$2,445.23","$4,689,500"
4,Cabernet Sauvignon,2014,"11,689.7","1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
5,,2013,"11,830.3","1,070.8","12,901.1","44,255.8","$2,462.99","$109,001,600"
6,Carignane,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
7,,2013,579.6,4.0,583.6,506.7,"$1,870.18","$947,700"
8,Malbec,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
9,,2013,425.7,109.4,535.1,"2,706.6","$2,356.19","$6,377,300"
10,Merlot,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"
11,,2013,"4,619.9",27.3,"4,647.2","18,784.5","$1,607.03","$30,187,300"
12,Meunier,2014,88.8,6.6,95.4,607.6,"$2,305.57","$1,400,900"
13,,2013,91.8,6.6,98.4,716.9,"$2,285.40","$1,638,500"
14,Petite Sirah,2014,630.1,55.1,685.2,"2,873.5","$2,548.12","$7,322,100"
15,,2013,598.3,83.5,681.8,"2,856.8","$2,477.06","$7,076,500"
16,Petite Verdot,2014,250.0,34.2,284.2,"1,251.1","$2,667.28","$3,337,100"
17,,2013,236.9,30.5,267.4,"1,120.0","$2,840.39","$3,181,300"
18,Pinot Noir,2014,"12,567.9","1,014.4","13,582.3","47,677.2","$3,251.49","$155,022,000"
19,,2013,"12,539.3",948.1,"13,487.4","54,826.8","$3,079.99","$168,866,000"
20,Sangiovese,2014,210.2,0.0,210.2,"1,211.9","$2,352.94","$2,851,600"
21,,2013,195.9,12.7,208.6,"1,141.1","$2,383.10","$2,719,400"
22,Syrah-Shiraz,2014,"1,649.5",9.8,"1,659.3","4,642.6","$2,314.44","$10,745,100"
23,,2013,"1,731.9",7.0,"1,738.9","4,835.8","$2,246.05","$10,861,500"
24,Zinfandel,2014,"5,015.8",112.1,"5,127.9","15,597.2","$2,543.78","$39,675,900"
25,,2013,"5,139.0",159.8,"5,298.8","20,172.3","$2,444.51","$49,311,400"
26,TOTAL ALL REDS,2014,"38,775.8","3,037.2","41,813.0","144,021.5","$2,685.05","$386,705,000"
27,Includes other reds,2013,"39,788.7","3,167.3","42,956.0","156,435.3","$2,558.50","$400,239,800"

,0,1,2,3,4,5,6,7
0,Top 12,,,Acreage,,,Production,
1,Red Varieties,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
2,Cabernet Franc,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
3,,2013,604.5,13.2,617.7,"1,917.8","$2,445.23","$4,689,500"
4,Cabernet Sauvignon,2014,"11,689.7","1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
5,,2013,"11,830.3","1,070.8","12,901.1","44,255.8","$2,462.99","$109,001,600"
6,Carignane,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
7,,2013,579.6,4.0,583.6,506.7,"$1,870.18","$947,700"
8,Malbec,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
9,,2013,425.7,109.4,535.1,"2,706.6","$2,356.19","$6,377,300"
10,Merlot,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"
11,,2013,"4,619.9",27.3,"4,647.2","18,784.5","$1,607.03","$30,187,300"
12,Meunier,2014,88.8,6.6,95.4,607.6,"$2,305.57","$1,400,900"
13,,2013,91.8,6.6,98.4,716.9,"$2,285.40","$1,638,500"
14,Petite Sirah,2014,630.1,55.1,685.2,"2,873.5","$2,548.12","$7,322,100"
15,,2013,598.3,83.5,681.8,"2,856.8","$2,477.06","$7,076,500"
16,Petite Verdot,2014,250.0,34.2,284.2,"1,251.1","$2,667.28","$3,337,100"
17,,2013,236.9,30.5,267.4,"1,120.0","$2,840.39","$3,181,300"
18,Pinot Noir,2014,"12,567.9","1,014.4","13,582.3","47,677.2","$3,251.49","$155,022,000"
19,,2013,"12,539.3",948.1,"13,487.4","54,826.8","$3,079.99","$168,866,000"
20,Sangiovese,2014,210.2,0.0,210.2,"1,211.9","$2,352.94","$2,851,600"
21,,2013,195.9,12.7,208.6,"1,141.1","$2,383.10","$2,719,400"
22,Syrah-Shiraz,2014,"1,649.5",9.8,"1,659.3","4,642.6","$2,314.44","$10,745,100"
23,,2013,"1,731.9",7.0,"1,738.9","4,835.8","$2,246.05","$10,861,500"
24,Zinfandel,2014,"5,015.8",112.1,"5,127.9","15,597.2","$2,543.78","$39,675,900"
25,,2013,"5,139.0",159.8,"5,298.8","20,172.3","$2,444.51","$49,311,400"
26,TOTAL ALL REDS,2014,"38,775.8","3,037.2","41,813.0","144,021.5","$2,685.05","$386,705,000"
27,Includes other reds,2013,"39,788.7","3,167.3","42,956.0","156,435.3","$2,558.50","$400,239,800"

,0,1,2,3,4,5,6,7
0,,,,Acreage,,,Production,
1,Red Varieties,Year,,Bearing Non-Bearing,Total,Tons,$/Ton,Total Value
2,Cabernet Franc,2011,655.9,6.7,662.6,"1,568.6","$ 2,209.15","$\n3,465,300"
3,,2010,653.9,14.3,668.2,"1,436.3","$ 2,166.55","$\n3,111,900"
4,Cabernet Sauvignon,2011,"11,726.8",291.5,"12,018.3","33,126.8","$ 2,111.24","$\n69,938,700"
5,,2010,"11,549.0",468.3,"12,017.3","37,933.3","$ 2,083.96","$\n79,051,500"
6,Carignane,2011,615.4,0.0,615.4,373.2,"$ 2,019.14","$\n753,600"
7,,2010,180.3,1.0,181.3,270.4,"$ 1,949.11","$\n527,100"
8,Malbec,2011,322.4,76.6,399.0,"1,110.5","$ 2,340.51","$\n2,599,200"
9,,2010,310.4,69.1,379.5,770.5,"$ 2,430.83","$\n1,873,000"
10,Merlot,2011,"5,126.6",23.4,"5,149.9","14,670.5","$ 1,380.85","$\n20,257,800"
11,,2010,"5,248.0",55.6,"5,303.6","17,440.9","$ 1,297.08","$\n22,622,300"
12,Meunier,2011,108.5,15.0,123.5,301.4,"$ 2,698.80","$\n813,500"
13,,2010,108.5,15.0,123.5,406.5,"$ 2,928.56","$\n1,190,500"
14,Petite Sirah,2011,575.0,22.2,597.1,"2,521.1","$ 2,325.25","$\n5,862,200"
15,,2010,522.6,37.7,560.3,"2,085.9","$ 2,377.94","$\n4,960,200"
16,Petite Verdot,2011,209.2,2.6,211.8,851.7,"$ 2,461.02","$\n2,096,100"
17,,2010,202.9,9.2,212.1,695.5,"$ 2,476.49","$\n1,722,400"
18,Pinot Noir,2011,"11,862.6",377.1,"12,239.7","28,350.2","$ 2,902.47","$\n82,285,700"
19,,2010,"11,456.0",675.5,"12,131.5","29,791.3","$ 2,825.12","$\n84,164,000"
20,Sangiovese,2011,89.5,36.5,126.0,845.2,"$ 2,204.51","$\n1,863,300"
21,,2010,259.7,48.4,308.1,983.6,"$ 2,244.09","$\n2,207,300"
22,Syrah-Shiraz,2011,"1,773.1",19.1,"1,792.3","3,614.0","$ 2,124.31","$\n7,677,300"
23,,2010,"1,791.6",51.7,"1,843.3","4,587.6","$ 2,030.22","$\n9,313,900"
24,,2011,"5,216.8",81.1,"5,297.9","13,101.0","$ 2,357.61","$\n30,887,100"
25,Zinfandel,,,,,,,
26,,2010,"5,055.0",112.5,"5,167.5","10,864.4","$ 2,260.27","$\n24,556,500"
27,,2011,"38,281.7",951.7,"39,233.4","101,818.5","$ 2,301.97","(a) $ 234,383,132"
28,TOTAL REDS,2010,"37,337.9*",1558.3,"38,896.1","108,497.4*","$ 2,211.08*","(a) $ 239,896,431*"

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/camelot/parsers/stream.py:365: UserWarning: No tables found in table area 2
  warnings.warn(f"No tables found in table area {table_idx + 1}")

,0,1,2,3,4,5,6,7,8,9
0,,,,Acreage,,,Pr,oduction,,
1,Red Varieties,Year,Bearing,Non-Bearing,Total,Tons,,$/Ton,,Total Value
2,Cabernet Franc,2010,653.9,14.3,668.2,"1,436.3",$,"2,166.55",,"3,111,900"
3,,2009,657.9,48.8,706.7,"1,935.6",$,"2,358.82",$,"4,565,800"
4,Cabernet Sauvignon,2010,"11,549.0",468.3,"12,017.3","37,933.3",$,"2,083.96",$,"79,051,500"
5,,2009,"11,658.5",730.5,"12,389.0","41,140.6",$,"2,280.67",$,"93,828,200"
6,Carignane,2010,180.3,1.0,181.3,270.4,$,"1,949.11",$,"527,100"
7,,2009,182.0,2.8,184.8,464.2,$,"1,919.43",$,"891,000"
8,Malbec,2010,310.4,69.1,379.5,770.5,$,"2,430.83",$,"1,873,000"
9,,2009,281.8,82.1,363.9,877.9,$,"2,491.49",$,"2,187,300"
10,Merlot,2010,"5,248.0",55.6,"5,303.6","17,440.9",$,"1,297.08",$,"22,622,300"
11,,2009,"5,736.9",109.1,"5,846.0","16,506.5",$,"1,507.00",$,"24,875,300"
12,Meunier,2010,108.5,15.0,123.5,406.5,$,"2,928.56",$,"1,190,500"
13,,2009,109.0,15.0,124.0,398.5,$,"3,056.21",$,"1,217,900"
14,Petite Sirah,2010,522.6,37.7,560.3,"2,085.9",$,"2,377.94",$,"4,960,200"
15,,2009,503.9,85.9,589.8,"2,300.6",$,"2,480.13",$,"5,705,800"
16,Petite Verdot,2010,202.9,9.2,212.1,695.5,$,"2,476.49",$,"1,722,400"
17,,2009,189.0,34.8,223.8,918.9,$,"2,778.24",$,"2,553,000"
18,Pinot Noir,2010,"11,456.0",675.5,"12,131.5","29,791.3",$,"2,825.12",$,"84,164,000"
19,,2009,"10,746.2","1,988.5","12,734.7","31,961.2",$,"3,043.08",$,"97,260,500"
20,Sangiovese,2010,259.7,48.4,308.1,983.6,$,"2,244.09",$,"2,207,300"
21,,2009,298.6,11.1,309.7,"1,210.6",$,"2,231.17",$,"2,701,100"
22,Syrah-Shiraz,2010,"1,791.6",51.7,"1,843.3","4,587.6",$,"2,030.22",$,"9,313,900"
23,,2009,"1,816.6",168.5,"1,985.1","5,563.3",$,"2,314.65",$,"12,877,100"
24,Zinfandel,2010,"5,055.0",112.5,"5,167.5","10,864.4",$,"2,260.27",$,"24,556,500"
25,,2009,"5,229.7",171.5,"5,401.2","15,637.4",$,"2,462.39",$,"38,505,400"
26,Other Reds,2010,466.6,48.0,514.6,"1,214.8",,,$,"9,416,500"
27,,2009,527.2,187.6,714.8,"1,839.7",,,$,"6,180,000"
28,,2010,"37,804.4","1,606.3","39,410.7","108,481.0\n(a",) $,"2,255.85 (a",) $,"244,717,100"
29,TOTAL REDS,2009,"37,937.2","3,636.2","41,573.4","120,717.0\n(a",) $,"2,430.05 (a",) $,"293,348,400"
30,(a) weighted average,,,,,,,,,

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/camelot/parsers/stream.py:365: UserWarning: No tables found in table area 2
  warnings.warn(f"No tables found in table area {table_idx + 1}")

,0,1,2,3,4,5,6,7,8,9
0,Winegrap,e Pro,ductio,n,,,,,,
1,,,,Acreage,,,Pr,oduction,,
2,R\ned Varieties,Year,Bearing,Non-Bearing,Total,Tons,,$/Ton,,Total Value
3,Cabernet Franc,2009,657.9,48.8,706.7,"1,935.6",$,"2,358.82",$,"4,565,800"
4,,2008,638.7,49.9,688.6,"1,594.8",$,"2,338.83",$,"3,730,000"
5,Cabernet Sauvignon,2009,"11,658.5",730.5,"12,389.0","41,140.6",$,"2,280.67",$,"93,828,200"
6,,2008,"11,576.0",678.4,"12,254.4","31,870.8",$,"2,321.51",$,"73,988,400"
7,Carignane,2009,182.0,2.8,184.8,464.2,$,"1,919.43",$,"891,000"
8,,2008,181.1,0.0,181.1,327.7,$,"1,944.90",$,"637,400"
9,Malbec,2009,281.8,82.1,363.9,877.9,$,"2,491.49",$,"2,187,300"
10,,2008,272.0,76.0,348.0,787.6,$,"2,550.60",$,"2,008,900"
11,Merlot,2009,"5,736.9",109.1,"5,846.0","16,506.5",$,"1,507.00",$,"24,875,300"
12,,2008,"5,875.6",133.4,"6,009.0","13,298.5",$,"1,555.48",$,"20,685,600"
13,Meunier,2009,109.0,15.0,124.0,398.5,$,"3,056.21",$,"1,217,900"
14,,2008,105.9,4.5,110.4,325.2,$,"2,769.47",$,"900,700"
15,Petite Sirah,2009,503.9,85.9,589.8,"2,300.6",$,"2,480.13",$,"5,705,800"
16,,2008,466.4,98.1,564.5,"1,905.9",$,"2,535.97",$,"4,833,400"
17,Petite Verdot,2009,189.0,34.8,223.8,918.9,$,"2,778.24",$,"2,553,000"
18,,2008,174.4,45.1,219.5,650.3,$,"2,707.89",$,"1,761,000"
19,Pinot Noir,2009,"10,746.2","1,988.5","12,734.7","31,961.2",$,"3,043.08",$,"97,260,500"
20,,2008,"10,293.2","2,242.5","12,535.7","29,441.5",$,"3,170.71",$,"93,350,500"
21,Sangiovese,2009,298.6,11.1,309.7,"1,210.6",$,"2,231.17",$,"2,701,100"
22,,2008,277.6,14.9,292.5,716.8,$,"2,226.54",$,"1,596,000"
23,Syrah-Shiraz,2009,"1,816.6",168.5,"1,985.1","5,563.3",$,"2,314.65",$,"12,877,100"
24,,2008,"1,770.6",216.4,"1,987.0","4,789.9",$,"2,331.26",$,"11,166,600"
25,Zinfandel,2009,"5,229.7",171.5,"5,401.2","15,637.4",$,"2,462.39",$,"38,505,400"
26,,2008,"5,384.5",237.1,"5,621.6","12,190.6",$,"2,485.66",$,"30,301,700"
27,Other Reds,2009,527.2,187.6,714.8,"1,839.7",,,$,"6,180,000"
28,,2008,512.7,80.7,593.4,"1,528.8",,,$,"2,476,400"
29,,2009,"37,937.2","3,636.2","41,573.4","120,717.0\n(a",) $,"2,430.05 (a",) $,"293,348,400"
30,TOTAL REDS,2008,"37,528.7","3,877.0","41,405.7","99,428.4\n(a",) $,"2,488.59 (a",) $,"247,436,600"
31,(a) weighted average,,TONS,,,,,,,

,0,1,2,3,4,5,6,7,8,9
0,,,,Acreage,,,Pr,oduction,,
1,Red Varieties,Year,Bearing,Non-Bearing,Total,Tons,,$/Ton,,Total Value
2,Cabernet Franc,2008,638.7,49.9,688.6,"1,594.8",$,"2,338.83",$,"3,730,000"
3,,2007,635.6,58.8,694.4,"2,066.5",$,"2,097.15",$,"4,333,800"
4,Cabernet Sauvignon,2008,"11,576.0",678.4,"12,254.4","31,870.8",$,"2,321.51",$,"73,988,400"
5,,2007,"11,405.0",688.7,"12,093.7","41,550.6",$,"2,237.73",$,"92,979,100"
6,Carignane,2008,181.1,0.0,181.1,327.7,$,"1,944.90",$,"637,400"
7,,2007,180.5,0.6,181.1,384.6,$,"1,861.81",$,"716,100"
8,Malbec,2008,272.0,76.0,348.0,787.6,$,"2,550.60",$,"2,008,900"
9,,2007,252.7,77.3,330.0,837.2,$,"2,487.87",$,"2,082,900"
10,Merlot,2008,"5,875.6",133.4,"6,009.0","13,298.5",$,"1,555.48",$,"20,685,600"
11,,2007,"6,206.6",211.8,"6,418.4","21,337.4",$,"1,452.25",$,"30,987,300"
12,Meunier,2008,105.9,4.5,110.4,325.2,$,"2,769.47",$,"900,700"
13,,2007,114.4,1.5,115.9,416.7,$,"2,476.94",$,"1,032,200"
14,Petite Sirah,2008,466.4,98.1,564.5,"1,905.9",$,"2,535.97",$,"4,833,400"
15,,2007,444.7,101.7,546.4,"2,320.1",$,"2,428.79",$,"5,635,100"
16,Petite Verdot,2008,174.4,45.1,219.5,650.3,$,"2,707.89",$,"1,761,000"
17,,2007,164.8,52.3,217.1,704.9,$,"2,688.20",$,"1,895,000"
18,Pinot Noir,2008,"10,293.2","2,242.5","12,535.7","29,441.5",$,"3,170.71",$,"93,350,500"
19,,2007,"10,198.1","1,612.3","11,810.3","29,486.9",$,"2,831.16",$,"83,482,200"
20,Sangiovese,2008,277.6,14.9,292.5,716.8,$,"2,226.54",$,"1,596,000"
21,,2007,275.7,13.9,289.6,937.5,$,"2,008.00",$,"1,882,500"
22,Syrah-Shiraz,2008,"1,770.6",216.4,"1,987.0","4,789.9",$,"2,331.26",$,"11,166,600"
23,,2007,"1,749.4",206.0,"1,955.4","7,860.4",$,"2,233.46",$,"17,555,900"
24,Zinfandel,2008,"5,384.5",237.1,"5,621.6","12,190.6",$,"2,485.66",$,"30,301,700"
25,,2007,"5,211.9",244.3,"5,456.2","14,591.5",$,"2,376.30",$,"34,673,800"
26,Other Reds,2008,512.7,80.7,593.4,"1,5828.8",$,"1,619.83",$,"2,476,400"
27,,2007,483.9,143.7,627.6,"1,754.6",$,"2,986.55",$,"5,240.200"
28,,2008,"37,528.7","3,877.0","41,405.7","99,428.4",$,"2,488.59 (a",) $,"247,436,600"
29,TOTAL REDS,2007,"37,323.3","3,412.8","40,736.1","124,248.9",$,"2,273.63 (a",) $,"282,496,100"
30,(a) weighted average,,,,,,,,,

,0,1,2,3,4,5,6,7,8,9
0,Winegrap,e Pr,oduct,ion,,,,,,
1,,,,Acreage,,,Pr,oduction,,
2,Red Varieties,Year,Bearing,Non-Bearing,Total,Tons,,$/Ton,,Total Value
3,Cabernet Franc,2007,635.6,58.8,694.4,"2,066.5",$,"2,097.15",$,"4,333,800"
4,,2006,679.1,59.2,738.9,"1,664.9",$,"2,395.21",$,"3,987,700"
5,Cabernet Sauvignon,2007,"11,405.0",688.7,"12,093.7","41,550.6",$,"2,237.73",$,"92,979,100"
6,,2006,"11,527.2",547.4,"12,074.6","38,410.3",$,"2,265.69",$,"87,025,900"
7,Carignane,2007,180.5,0.6,181.1,384.6,$,"1,861.81",$,"716,100"
8,,2006,188.0,1.6,189.6,394.4,$,"1,804.52",$,"711,800"
9,Malbec,2007,252.7,77.3,330.0,837.2,$,"2,487.87",$,"2,082,900"
10,,2006,241.1,43.3,284.4,"1,393.0",$,"2,483.61",$,"3,459,700"
11,Merlot,2007,"6,206.6",211.8,"6,418.4","21,337.4",$,"1,452.25",$,"30,987,300"
12,,2006,"6,697.4",197.5,"6,894.9","26,015.2",$,"1,529.52",$,"39,790,800"
13,Meunier,2007,114.4,1.5,115.9,416.7,$,"2,476.94",$,"1,032,200"
14,,2006,103.0,3.0,106.0,682.8,$,"2,166.97",$,"1,479,700"
15,Petite Sirah,2007,444.7,101.7,546.4,"2,320.1",$,"2,428.79",$,"5,635,100"
16,,2006,417.3,65.7,483.0,"1,708.7",$,"2,371.27",$,"4,051,800"
17,Petite Verdot,2007,164.8,52.3,217.1,704.9,$,"2,688.20",$,"1,895,000"
18,,2006,167.9,44.7,212.6,651.2,$,"2,677.21",$,"1,743,400"
19,Pinot Noir,2007,"10,198.1","1,612.3","11,810.3","29,486.9",$,"2,831.16",$,"83,482,200"
20,,2006,"9,884.7","1,146.2","11,030.9","38,453.8",$,"2,507.31",$,"96,415,600"
21,Sangiovese,2007,275.7,13.9,289.6,937.5,$,"2,008.00",$,"1,882,500"
22,,2006,288.5,6.8,295.3,"1,275.1",$,"1,924.10",$,"2,453,500"
23,Syrah-Shiraz,2007,"1,749.4",206.0,"1,955.4","7,860.4",$,"2,233.46",$,"17,555,900"
24,,2006,"1,804.9",129.1,"1,934.0","6,844.1",$,"2,231.25",$,"15,270,900"
25,Zinfandel,2007,"5,211.9",244.3,"5,456.2","14,591.5",$,"2,376.30",$,"34,673,800"
26,,2006,"5,433.0",236.4,"5,669.4","16,683.7",$,"2,309.13",$,"38,524,900"
27,Other Reds,2007,483.9,143.7,627.6,"1,754.6",$,"2,986.55",$,"5,240,200"
28,,2006,517.5,37.3,554.8,"1,469.6",$,"2,110.57",$,"3,101,700"
29,,2007,"37,323.3","3,412.8","40,736.1","124,248.9",$ 2,",273.63 (a)",$,"282,496,100"
30,TOTAL REDS,2006,"37,950.2","2,518.2","40,468.4","135,646.8",$,"2,197.01 (a)",$,"298,017,400"
31,(a) weighted average,,,,,,,,,

,0,1,2,3,4,5,6,7,8
0,,,,Acres,,,P,roduction,
1,Variety,Year,N\nBearing,on-Bearing,Total,Tons,,$/Ton,Total Value
2,Cabernet Franc,2006,679.7,59.2,738.9,"1,664.9",$,"2,395.21","$ \n3,987,800"
3,,2005,673.1,64.8,737.9,"2,318.8",$,"2,506.83","$ \n5,812,900"
4,Cabernet Sauvignon,2006,"11,527.2",547.4,"12,074.6","38,410.3",$,"2,265.69","$ \n87,025,900"
5,,2005,"11,404.7",875.4,"12,280.1","45,577.2",$,"2,305.27","$ 105,067,800"
6,Carignane,2006,188.0,1.6,189.6,394.4,$,"1,804.52","$ \n711,800"
7,,2005,181.8,8.8,190.6,440.6,$,"1,888.61","$ \n832,200"
8,Malbec,2006,241.1,43.3,284.4,"1,393.0",$,"2,483.61","$ \n3,459,700"
9,,2005,234.1,36.1,270.2,731.8,$,"2,496.31","$ \n1,826,800"
10,Merlot,2006,"6,697.4",197.5,"6,894.9","26,015.2",$,"1,529.52","$ \n39,790,800"
11,,2005,"6,971.9",315.6,"7,287.6","31,656.3",$,"1,591.72","$ \n50,388,000"
12,Meunier,2006,103.0,3.0,106.0,682.8,$,"2,166.97","$ \n1,479,700"
13,,2005,109.0,13.0,122.0,332.2,$,"1,991.00","$ \n661,500"
14,Petite Sirah,2006,417.3,65.7,483.0,"1,708.7",$,"2,371.27","$ \n4,051,800"
15,,2005,391.2,63.4,454.6,"2,125.4",$,"2,293.95","$ \n4,875,600"
16,Petite Verdot,2006,167.9,44.7,212.6,651.2,$,"2,677.21","$ \n1,743,400"
17,,2005,155.5,18.4,173.8,634.6,$,"2,608.88","$ \n1,655,600"
18,Pinot Noir,2006,"9,884.7","1,146.2","11,030.9","38,453.8",$,"2,507.31","$ \n96,415,600"
19,,2005,"9,247.2","1,228.9","10,476.1","26,944.3",$,"2,128.99","$ \n57,364,200"
20,Sangiovese,2006,288.5,6.8,295.3,"1,275.1",$,"1,924.10","$ \n2,453,500"
21,,2005,300.4,6.8,307.2,"1,528.5",$,"1,797.84","$ \n2,748,000"
22,Syrah-Shiraz,2006,"1,804.9",129.1,"1,934.0","6,844.1",$,"2,231.25","$ \n15,270,900"
23,,2005,"1,594.9",268.9,"1,863.8","7,959.4",$,"2,145.47","$ \n17,076,700"
24,Zinfandel,2006,"5,433.0",236.4,"5,669.4","16,683.7",$,"2,309.13","$ \n38,524,900"
25,,2005,"5,044.2",504.8,"5,549.0","17,866.5",$,"2,306.54","$ \n41,209,800"
26,Other Reds,2006,517.5,37.3,554.8,"1,469.6",$,"2,110.57","$ \n3,101,700"
27,,2005,586.7,48.0,634.7,"1,827.6",$,"1,260.29","$ \n2,303,300"
28,,2006,"37,950.2","2,518.2","40,468.4","135,646.8",$,"2,197.01","$ 298,017,400"
29,TOTAL REDS,2005,"36,894.7*","3,453.0*","40,347.6*","139,943.2",$,"2,085.72","$ 291,882,400"
30,* revised,,,,,,,,

,0,1,2,3,4,5,6,7,8,9
0,,,,Acres,,,,Productio,n,
1,Variety,Year,Bearing\nN,on-Bearing,Total,Tons,,$/Ton,,Total Value
2,,2005,701.4,64.8,766.2,"2,318.8",$,"2,506.83",$,"5,812,900"
3,Cabernet Franc,2004,603.1,87.2,690.2,"1,692.1",$,"2,498.88",$,"4,228,400"
4,,2005,"11,791.6",875.4,"12,667.0","45,577.2",$,"2,305.27",$,"105,067,800"
5,Cabernet Sauv.,2004,"10,216.0","1,910.2","12,126.2","30,561.3",$,"2,397.71",$,"73,277,200"
6,,2005,189.3,8.8,198.1,440.6,$,"1,888.61",$,"832,200"
7,Carignane,2004,185.7,9.1,194.8,418.9,$,"1,477.99",$,"619,200"
8,,2005,249.3,36.1,285.4,731.8,$,"2,496.31",$,"1,826,800"
9,Malbec,2004,206.5,67.0,273.5,430.5,$,"2,419.96",$,"1,041,800"
10,,2005,"7,137.8",315.6,"7,453.4","31,656.3",$,"1,591.72",$,"50,388,000"
11,Merlot,2004,"6,873.0",518.4,"7,391.4","22,855.2",$,"1,663.90",$,"38,028,800"
12,,2005,119.0,13.0,132.0,332.2,$,"1,991.00",$,"661,500"
13,Meunier,2004,109.0,14.0,123.0,471.3,$,"1,951.39",$,"919,700"
14,,2005,418.1,63.4,481.5,"2,125.4",$,"2,293.95",$,"4,875,600"
15,Petite Sirah,2004,356.0,93.0,449.0,"1,256.0",$,"2,445.12",$,"3,071,100"
16,,2005,162.8,18.4,181.2,634.6,$,"2,608.88",$,"1,655,600"
17,Petite Verdot,2004,134.6,37.1,171.6,444.8,$,"2,685.95",$,"1,194,800"
18,,2005,"9,887.7","1,228.9","11,116.6","26,944.3",$,"2,128.99",$,"57,364,200"
19,Pinot Noir,2004,"8,061.6","2,074.9","10,136.5","22,672.7",$,"1,974.75",$,"44,773,000"
20,,2005,318.4,6.8,325.2,"1,528.5",$,"1,797.84",$,"2,748,000"
21,Sangiovese,2004,336.1,33.2,369.3,"1,107.2",$,"2,195.35",$,"2,430,700"
22,,2005,"1,788.7",268.9,"2,057.6","7,959.4",$,"2,145.47",$,"17,076,700"
23,Syrah-Shiraz,2004,"1,321.7",497.9,"1,819.6","5,849.8",$,"2,041.91",$,"11,944,800"
24,,2005,"5,326.6",504.8,"5,831.4","17,866.5",$,"2,306.54",$,"41,209,800"
25,Zinfandel,2004,"4,429.3",732.6,"5,161.9","11,783.2",$,"2,301.63",$,"27,120,600"
26,,2005,890.6,723.5,"1,614.0","1,827.6",$,"1,260.29",$,"2,303,300"
27,Other Reds,2004,505.3,734.6,"1,239.9","1,520.2",$,"2,557.90",$,"2,888,400"
28,,2005,"38,981.1","4,128.5","43,109.6","139,943.2",$,"2,085.72",$,"291,882,400"
29,TOTAL REDS,2004,"33,337.8","6,809.1","40,146.9","101,063.2",$,"2,093.13",$,"211,538,500"

,0,1,2,3,4,5,6,7
0,,,,Acres,,,Production,
1,VARIETY,YEAR,BEARING,NON-BEARING,TOTAL,TONS,$ PER TON,TOTAL VALUE
2,Cabernet Franc,2004,603.1,87.2,690.2,"1,692.1","$ \n2,498.88","$ \n4,228,400"
3,,2003,612.0,75.0,687.0,"1,813.2","$ \n2,580.74","$ \n4,679,400"
4,Cabernet Sauv.,2004,"10,216.0","1,910.2","12,126.2","30,561.3","$ \n2,397.71","$ \n73,277,200"
5,,2003,"10,554.0","1,682.0","12,236.0","36,471.4","$ \n2,537.94","$ \n92,562,300"
6,Carignane,2004,185.7,9.1,194.8,418.9,"$ \n1,477.99","$ \n619,200"
7,,2003,183.0,3.1,186.1,397.5,"$ \n1,718.81","$ \n683,300"
8,Malbec,2004,206.5,67.0,273.5,430.5,"$ \n2,419.96","$ \n1,041,800"
9,,2003,244.9,67.0,311.9,146.7,"$ \n2,503.24","$ \n367,300"
10,Merlot,2004,"6,873.0",518.4,"7,391.4","22,855.2","$ \n1,663.90","$ \n38,028,800"
11,,2003,"7,027.0",402.0,"7,429.0","20,917.5","$ \n1,768.89","$ \n37,000,800"
12,Meunier,2004,109.0,14.0,123.0,471.3,"$ \n1,951.39","$ \n919,700"
13,,2003,109.0,13.0,122.0,572.6,"$ \n2,060.14","$ \n1,179,700"
14,Petite Sirah,2004,356.0,93.0,449.0,"1,256.0","$ \n2,445.12","$ \n3,071,100"
15,,2003,357.0,55.0,412.0,"1,194.3","$ \n2,503.94","$ \n2,990,500"
16,Petite Verdot,2004,134.6,37.1,171.6,444.8,"$ \n2,685.95","$ \n1,194,800"
17,,2003,144.0,31.0,175.0,400.1,"$ \n2,676.19","$ \n1,070,800"
18,Pinot Noir,2004,"8,061.6","2,074.9","10,136.5","22,672.7","$ \n1,974.75","$ \n44,773,000"
19,,2003,"8,328.0","1,784.0","10,112.0","18,759.1","$ \n2,011.54","$ \n37,734,700"
20,Sangiovese,2004,336.1,33.2,369.3,"1,107.2","$ \n2,195.35","$ \n2,430,700"
21,,2003,407.0,33.0,440.0,"1,374.2","$ \n2,040.91","$ \n2,804,700"
22,Syrah-shiraz,2004,"1,321.7",497.9,"1,819.6","5,849.8","$ \n2,041.91","$ \n11,944,800"
23,,2003,"1,359.0",433.0,"1,792.0","5,666.2","$ \n2,060.09","$ \n11,672,900"
24,Zinfandel,2004,"4,429.3",732.6,"5,161.9","11,783.2","$ \n2,301.63","$ \n27,120,600"
25,,2003,"4,504.0",607.0,"5,111.0","11,561.3","$ \n2,334.96","$ \n26,995,200"
26,Other Reds,2004,505.3,734.6,"1,239.9","1,520.2","$ \n2,557.90","$ \n2,888,400"
27,,2003,816.0,718.0,"1,535.0","1,684.9","$ \n2,152.29","$ \n3,313,900"
28,,2004,"33,337.8","6,809.1","40,146.9","101,063.2","$ \n2,093.13","$ \n211,538,500"
29,TOTAL REDS,2003,"34,443.0","5,836.0","40,280.0","100,863.9","$ \n2,211.45","$ \n223,055,500"

,0,1,2,3,4,5,6,7
0,,,,Acres,,,Productio,n
1,,,,NON-,,,DOLLARS,TOTAL
2,VARIETY,YEAR,BEARING,BEARING,TOTAL,TONS,PER TON,VALUE
3,Cabernet Franc,2003,612,75,687,"1,813.20","$ \n2,580.74","$ \n4,679,400"
4,,2002,560,118,678,"1,927.50","$ \n2,532.25","$ \n4,881,000"
5,Cabernet Sauv.,2003,"10,554","1,682","12,237","36,471.40","$ \n2,537.94","$ \n92,562,300"
6,,2002,"9,018","3,125","12,143","32,258.10","$ \n2,694.93","$ \n86,933,400"
7,Carignane,2003,183,3,186,397.50,"$ \n1,718.81","$ \n683,300"
8,,2002,188,3,191,498.70,"$ \n1,562.64","$ \n779,300"
9,Merlot,2003,"7,027",402,"7,429","20,917.50","$ \n1,768.89","$ \n37,000,800"
10,,2002,"6,698",712,"7,410","29,037.30","$ \n1,965.47","$ \n57,072,000"
11,Meunier,2003,109,13,122,572.60,"$ \n2,060.14","$ \n1,179,700"
12,,2002,109,3,112,426.50,"$ \n2,164.26","$ \n923,100"
13,Napa Gamay,2003,42,0,42,51.60,"$ \n1,060.86","$ \n54,800"
14,,2002,49,0,49,93.90,"$ \n1,089.40","$ \n102,300"
15,Petite Sirah,2003,357,55,412,"1,194.30","$ \n2,503.94","$ \n2,990,500"
16,,2002,313,83,397,"1,083.60","$ \n2,534.18","$ \n2,746,100"
17,Petite Verdot,2003,144,31,175,400.10,"$ \n2,676.19","$ \n1,070,800"
18,,2002,87,86,174,308.80,"$ \n2,560.45","$ \n790,700"
19,Pinot Noir,2003,"8,328","1,784","10,113","18,759.10","$ \n2,011.54","$ \n37,734,700"
20,,2002,"6,434","3,821","10,255","19,571.00","$ \n2,131.66","$ \n41,718,800"
21,Sangiovese,2003,407,33,440,"1,374.20","$ \n2,040.91","$ \n2,804,700"
22,,2002,386,66,453,"1,791.90","$ \n2,048.31","$ \n3,670,400"
23,Syrah-shiraz,2003,"1,359",433,"1,792","5,666.20","$ \n2,060.09","$ \n11,672,900"
24,,2002,"1,040",717,"1,758","5,424.40","$ \n2,254.26","$ \n12,228,100"
25,Zinfandel,2003,"4,504",607,"5,111","11,561.30","$ \n2,334.96","$ \n26,995,200"
26,,2002,"4,300",828,"5,128","13,384.60","$ \n2,494.52","$ \n33,388,200"
27,Other Reds,2003,816,718,"1,535","1,684.90","$ \n2,152.29","$ \n3,626,400"
28,,2002,651,832,"1,483","2,011.30","$ \n2,436.88","$ \n4,901,300"
29,Total Reds,2003,"34,443","5,836","40,280","100,863.90","$ \n2,211.45","$ \n223,055,500"
30,,2002,"29,834","10,395","40,230","107,817.60","$ \n2,319.98","$ \n250,134,700"
31,Total All Wine,2003,"52,176","7,797","59,973","160,768.10","$ \n1,947.38","$ \n313,076,600"
32,Grapes,2002,"46,587","13,304","59,891","183,139.10","$ \n2,055.39","$ \n376,422,300"

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/camelot/parsers/stream.py:365: UserWarning: No tables found in table area 2
  warnings.warn(f"No tables found in table area {table_idx + 1}")

,0,1,2,3,4,5,6,7,8,9
0,,,A,cres,,,,Production,,
1,,,,NON-,,,D,OLLARS,,TOTAL
2,VARIETY,YEAR,BEARING \nB,EARING,TOTAL,TONS,P,ER TON,,VALUE
3,Cabernet Franc,2002,560,118,678,"1,928",$,"2,532.25",$,"4,881,000"
4,,2001,503,137,640,"2,309",$,"2,424.10",$,"5,597,300"
5,Cabernet Sauv.,2002,"9,018","3,125","12,143","32,258",$,"2,694.93",$,"86,933,400"
6,,2001,"7,937","4,018","11,955","32,194",$,"2,698.66",$,"86,881,500"
7,Carignane,2002,188,3,191,499,$,"1,562.64",$,"779,300"
8,,2001,182,2,184,587,$,"1,529.01",$,"896,800"
9,Merlot,2002,"6,698",712,"7,410","29,037",$,"1,965.47",$,"57,072,000"
10,,2001,"6,414",962,"7,376","27,879",$,"2,136.86",$,"59,573,800"
11,Meunier,2002,109,3,112,427,$,"2,164.26",$,"923,100"
12,,2001,111,3,114,566,$,"1,983.57",$,"1,122,200"
13,Napa Gamay,2002,49,0,49,94,$,"1,089.40",$,"102,300"
14,,2001,91,0,91,149,$,"1,289.12",$,"192,600"
15,Petite Sirah,2002,313,83,397,"1,084",$,"2,534.18",$,"2,746,100"
16,,2001,293,90,383,"1,007",$,"2,379.44",$,"2,395,900"
17,Petite Verdot,2002,87,86,174,309,$,"2,560.45",$,"790,700"
18,,2001,78,92,171,308,$,"2,408.91",$,"743,000"
19,Pinot Noir,2002,"6,434","3,821","10,255","19,571",$,"2,131.66",$,"41,718,800"
20,,2001,"5,811","4,554","10,365","20,861",$,"2,219.03",$,"46,290,600"
21,Sangiovese,2002,386,66,453,"1,792",$,"2,048.31",$,"3,670,400"
22,,2001,366,70,436,"1,376",$,"2,020.35",$,"2,779,600"
23,Syrah-shiraz,2002,"1,040",717,"1,758","5,424",$,"2,254.26",$,"12,228,100"
24,,2001,824,856,"1,680","4,195",$,"2,260.98",$,"9,483,700"
25,Zinfandel,2002,"4,300",828,"5,128","13,385",$,"2,494.52",$,"33,388,200"
26,,2001,"4,145",885,"5,030","14,287",$,"2,456.58",$,"35,096,500"
27,Other Reds,2002,651,832,"1,483","2,011",$,"2,436.88",$,"4,901,300"
28,,2001,523,180,703,"1,995",$,"1,962.80",$,"3,914,800"
29,Total Reds,2002,"29,834","10,395","40,230","107,818",$,"2,319.98",$,"250,134,700"
30,,2001,"27,279","11,848","39,127","107,712",$,"2,367.14",$,"254,968,300"
31,Total All Wine,2002,"46,587","13,304","59,891","183,139",$,"2,055.39",$,"376,422,300"
32,Grapes,2001,"43,589","15,076","58,665","173,583",$,"2,156.83",$,"374,389,700"

,0,1,2,3,4,5,6,7
0,,,A,cres,,,Production,
1,,,,NON-,,,DOLLARS,TOTAL
2,VARIETY,YEAR,BEARING\nB,EARING,TOTAL,TONS,PER TON,VALUE
3,Cabernet Franc,2001,503,137,640,"2,309","$ \n2,424.10","$ \n5,597,300"
4,,2000,523,151,674,"2,097","$ \n2,226.53","$ \n4,668,600"
5,Cabernet Sauv.,2001,"7,937","4,018","11,955","32,194","$ \n2,698.66","$ \n86,881,500"
6,,2000,"7,328","3,688","11,016","32,772","$ \n2,417.96","$ \n79,240,400"
7,Carignane,2001,182,2,184,587,"$ \n1,529.01","$ \n896,800"
8,,2000,196,1,197,766,"$ \n1,391.55","$ \n1,065,400"
9,Merlot,2001,"6,414",962,"7,376","27,879","$ \n2,136.86","$ \n59,573,800"
10,,2000,"6,564","1,058","7,622","31,480","$ \n2,019.29","$ \n63,566,200"
11,Meunier,2001,111,3,114,566,"$ \n1,983.57","$ \n1,122,200"
12,,2000,129,17,146,637,"$ \n2,069.27","$ \n1,318,700"
13,Napa Gamay,2001,91,0,91,149,"$ \n1,289.12","$ \n192,600"
14,,2000,84,0,84,195,"$ \n1,143.58","$ \n222,500"
15,Petite Sirah,2001,293,90,383,"1,007","$ \n2,379.44","$ \n2,395,900"
16,,2000,280,86,366,"1,073","$ \n2,127.81","$ \n2,284,000"
17,Petite Verdot,2001,78,92,171,308,"$ \n2,408.91","$ \n743,000"
18,,2000,86,77,163,282,"$ \n2,176.29","$ \n614,000"
19,Pinot Noir,2001,"5,811","4,554","10,365","20,861","$ \n2,219.03","$ \n46,290,600"
20,,2000,"4,973","3,631","8,604","17,520","$ \n2,094.39","$ \n36,692,700"
21,Sangiovese,2001,366,70,436,"1,376","$ \n2,020.35","$ \n2,779,600"
22,,2000,281,68,349,"1,791","$ \n1,859.57","$ \n3,331,000"
23,Syrah-shiraz,2001,824,856,"1,680","4,195","$ \n2,260.98","$ \n9,483,700"
24,,2000,559,371,930,"3,349","$ \n2,171.65","$ \n7,272,000"
25,Zinfandel,2001,"4,145",885,"5,030","14,287","$ \n2,456.58","$ \n35,096,500"
26,,2000,"4,478",665,"5,143","13,223","$ \n2,143.10","$ \n28,337,800"
27,Other Reds,2001,523,180,703,"1,995","$ \n1,962.80","$ \n3,914,800"
28,,2000,455,319,774,"1,844","$ \n2,036.69","$ \n3,755,200"
29,Total Reds,2001,"27,279","11,848","39,127","107,712","$ \n2,367.14","$ \n254,968,300"
30,,2000,"25,936","10,132","36,068","107,027","$ \n2,188.11","$ \n234,187,000"
31,Total All Wine,2001,"43,589","15,076","58,665","173,583","$ \n2,156.83","$ \n374,389,700"
32,Grapes,2000,"42,221","13,656","55,877","190,789","$ \n2,043.38","$ \n389,853,900"

finish reading pdf files

In [5]:
def rename_replace_varietal_column(table, year):

    if year == 2016:
        table.columns = ['0', '1', '2', '3', '4', '5', '6', '7']
        # For 2016 crop report:
        # temp is non-bearing
        table['Temp'] = table['3']  # Create a temporary column and store 'Bearing' values
        table['3'] = table['2']  # Move 'Non-Bearing' values to 'Bearing' column
        table['2'] = table['Temp']  # Move temporary values to 'Non-Bearing' column
        table.drop('Temp', axis=1, inplace=True)  # Drop the temporary column
        
    elif year <= 2010:
        if year != 2006 and year != 2004 and year != 2003 and year != 2001:
            table.columns = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
            table['7'] = table['6'] + table['7']
            table['9'] = table['8'] + table['9']
            table = table.drop(['6', '8'], axis=1)
        elif year == 2006:
            table.columns = ['0', '1', '2', '3', '4', '5', '6', '7', '8']
            table['7'] = table['6'] + table['7']
            table = table.drop(['6'], axis=1)

    new_columns = ['Varietal', 'Year', 'Bearing' , 'Non-Bearing', 'Total', 'Tons', '$/Ton', 'Total Value']
    data = table.rename(columns=dict(zip(table.columns,new_columns)))

    if year == 2011:
        # 2011 specific fixes
        # 24		2011	5,216.8	81.1	5,297.9	13,101.0	$ 2,357.61	$\n30,887,100
        # 25	Zinfandel
        data.loc[24][0] = data.loc[25][0]
        data.loc[27][0] = data.loc[28][0]
        data.loc[28][0] = ''

    elif year <= 2010 and year != 2007 and year != 2005:
        # for 2010; similar for 2009
        # 28		2010	37,804.4	1,606.3	39,410.7	108,481.0\n(a	) $2,255.85 (a	) $244,717,100
        # 29	TOTAL REDS	2009	37,937.2	3,636.2	41,573.4	120,717.0\n(a	) $2,430.05 (a	) $293,348,400	
        # 	
        if year == 2003 or year == 2002 or year == 2001:
            # specific for 2003, 2002, 2001: drop the total all wine grapes row
            data = data[:28]
        data.loc[28][0] = data.loc[29][0]
        data.loc[29][0] = ''
        
    elif year == 2007:
        data.loc[29][0] = data.loc[30][0]
        data.loc[30][0] = ''

    # data drop empty row
    data = data.query("Year != '' and Bearing != '' and Total != '' and Tons != ''")

    data['Varietal'] = data['Varietal'].replace('Mataro/', 'Mataro/Mouvedere')
    data['Varietal'] = data['Varietal'].replace('Cabernet', 'Cabernet Sauvignon')

    # for 2016 only; ignored when dataset does not contain these strings
     # for 2016; Sangiovese/Sangiove to Sangiovese 
    data['Varietal'] = data['Varietal'].replace('Sangiovese/', 'Sangiovese')
    # for 2016 Syrah - Shiraz to Syrah-Shiraz ; 
    data['Varietal'] = data['Varietal'].replace('Syrah - Shiraz', 'Syrah-Shiraz')
    data['Varietal'] = data['Varietal'].replace('TOTAL REDS', 'TOTAL ALL REDS')

    # for 2005 and 2004 
    data['Varietal'] = data['Varietal'].replace('Cabernet Sauv.', 'Cabernet Sauvigno')

    # added Mourvedere (a), Sangioveto bc of 2016
    data['Varietal'] = data['Varietal'].replace(['', 'including other reds', 'Mouvedere', 'Mourvedere (a)', 'Sauvignon', 'Sangioveto'], np.nan)
    data = data.reset_index(drop=True)

    # duplicate each variable twice because there is empty space after each variable 
    # For example: Zinfandel 2015 2014 to Zinfandel 2015 Zinfandel 2014
    data['Varietal'] = data['Varietal'].dropna().repeat(2).reset_index(drop=True)

    return data

def add_shift_county_color_column(data):

    # add columns to last and pop
    data['County'] = 'Sonoma'
    first_column = data.pop('County')
    data['Grape Color'] = 'Red'
    third_column = data.pop('Grape Color')

    # put county as first column, grape color as 3rd
    data.insert(0, 'County', first_column)
    data.insert(2, 'Grape Color', third_column)
    return data

def fix_incorrect_digits(data, year):
    # if exist a string that has empty space, add a '.' to complete the number
    
    if year == 2016:
        data['Bearing'] = data['Bearing'].str.replace(' .', '.', regex=False)
        data['Bearing'] = data['Bearing'].str.replace('--', '0.0', regex=False)
        data['Non-Bearing'] = data['Non-Bearing'].str.replace(' .', '.', regex=False)
        data['Non-Bearing'] = data['Non-Bearing'].str.replace('--', '0.0', regex=False)

        data['Total'] = data['Total'].str.replace(' .', '.', regex=False)
        data['Total'] = data['Total'].str.replace('--', '0.0', regex=False)
        data['Tons'] = data['Tons'].str.replace(' ', '', regex=False)
        data['$/Ton'] = data['$/Ton'].str.replace(' .', '.', regex=False)
        data['Total Value'] = data['Total Value'].str.replace(' ', ',')
    elif year == 2015:
        data['$/Ton'] = data['$/Ton'].replace('$2.525.16', '$2,525.16')
        data['$/Ton'] = data['$/Ton'].replace('$3,525,42', '$3,525.42')
        data['Bearing'] = data['Bearing'].replace('11 689.7', '11,689.7')
        

    elif year == 2011:
        # for 2011 only 
        data['Bearing'] = data['Bearing'].str.replace(' ', '.')
        data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
        data['Total'] = data['Total'].str.replace(' ', '.')
        data['Tons'] = data['Tons'].str.replace(' ', '.')
        data['$/Ton'] = data['$/Ton'].str.replace(' ', '')
        # data['Total Value'] = data['Total Value'].str.replace(' ', ',')

        # specific for 2011
        data['Bearing'] = data['Bearing'].str.replace('*', '', regex=False)
        data['Tons'] = data['Tons'].str.replace('*', '', regex=False)
        data['$/Ton'] = data['$/Ton'].str.replace('*', '', regex=False)
        data['Total Value'] = data['Total Value'].str.replace('\n', '', regex=False)
        data['Total Value'] = data['Total Value'].str.replace('(a)  $ ', '$', regex=False)
        data['Total Value'] = data['Total Value'].str.replace('*', '', regex=False)  
    elif year <= 2010:
        data['Bearing'] = data['Bearing'].str.replace(' ', '.')
        data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
        data['Total'] = data['Total'].str.replace(' ', '.')

        # # specific for 2010, 2009, 2008
        data['Tons'] = data['Tons'].str.replace('\n(a', '', regex=False)
        
        data['$/Ton'] = data['$/Ton'].str.replace(') ', '', regex=False)
        data['$/Ton'] = data['$/Ton'].str.replace(' (a', '', regex=False)
        data['$/Ton']  = data['$/Ton'].replace('', '$0.0', regex=False)
        
        # specific for 2007
        data['$/Ton'] = data['$/Ton'].str.replace(' (a)', '', regex=False)
        data['$/Ton'] = data['$/Ton'].str.replace(')', '', regex=False)
        data['Total Value'] = data['Total Value'].str.replace(') ', '', regex=False)
        data['Total Value'] = data['Total Value'].str.replace('5,240.200', '5,240,200', regex=False)

        # specific for 2006:
        data['Bearing'] = data['Bearing'].str.replace('*', '', regex=False)
        data['Total'] = data['Total'].str.replace('*', '', regex=False)
        data['$/Ton'] = data['$/Ton'].str.replace(' (a)', '', regex=False)
        data['Total Value'] = data['Total Value'].str.replace(' \n', '', regex=False)
        data['Total Value'] = data['Total Value'].str.replace(' ', '', regex=False)

        # specific for 2004:
        data['$/Ton'] = data['$/Ton'].str.replace(' \n', '', regex=False)
        data['$/Ton'] = data['$/Ton'].str.replace(' ', '', regex=False)

        data['Total Value'] = data['Total Value'].apply(lambda x: '$' + x if '$' not in x else x)   
    else:
        data['Bearing'] = data['Bearing'].str.replace(' ', '.')
        data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
        data['Total'] = data['Total'].str.replace(' ', '.')
        data['Tons'] = data['Tons'].str.replace(' ', '.')
        data['$/Ton'] = data['$/Ton'].str.replace(' ', '.')
        data['Total Value'] = data['Total Value'].str.replace(' ', ',')
    return data

In [6]:
# for <= 2016 we need to do it separately because of formatting 

combined_data_up_to_2017 = pd.DataFrame()
combined_data_up_to_2001 = pd.DataFrame()

# this goes up to 2017 files
for table, year in zip(table_list, sonoma_data['Year']):
    # 2021 - 2017 has a pattern where first 3 rows didn't matter
    
    if year >= 2017:
        table.drop([0,1,2], axis=0, inplace=True)

        # rename column names
        data_varietal_replaced = rename_replace_varietal_column(table, year)
        data_shifted = add_shift_county_color_column(data_varietal_replaced)

        # if exist a string that has empty space, add a '.' to complete the number
        data = fix_incorrect_digits(data_shifted, year)

        print(f'number of row for year {year} table is: {len(data)}')

        combined_data_up_to_2017 = pd.concat([combined_data_up_to_2017, data])

        # display(data)
        # display(combined_data_up_to_2017)
        
    # skips 2012 and 2013, their PDFs are not extractable
    elif year <= 2016 and year != 2013 and year != 2012:
        if year == 2009 or year == 2007 or year == 2003 or year == 2002 or year == 2001:
            table.drop([0,1,2], axis=0, inplace=True)
        else:
            table.drop([0,1], axis=0, inplace=True)
            
        # rename column names
        data_varietal_replaced = rename_replace_varietal_column(table, year)
        data_shifted = add_shift_county_color_column(data_varietal_replaced)

        # if exist a string that has empty space, add a '.' to complete the number
        data = fix_incorrect_digits(data_shifted, year)

        print(f'number of row for year {year} table is: {len(data)}')
        display(data)

        combined_data_up_to_2001 = pd.concat([combined_data_up_to_2001, data])

number of row for year 2021 table is: 28
number of row for year 2020 table is: 28
number of row for year 2019 table is: 28
number of row for year 2018 table is: 28
number of row for year 2017 table is: 28
number of row for year 2016 table is: 26

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Pinot Noir,Red,2016,"13,343.1",385.2,"13,728.3","42,566.3","$3,680.50","$156,665,300"
1,Sonoma,Pinot Noir,Red,2015,"12,850.8",750.0,"13,600.8","30,667.2","$3,525.42","$108,114,800"
2,Sonoma,Cabernet Sauvignon,Red,2016,"12,456.7",560.0,"13,016.7","41,575.7","$2,964.60","$123,255,300"
3,Sonoma,Cabernet Sauvignon,Red,2015,"11,808.8","1,014.7","12,823.5","32,947.3","$2,724.17","$89,754,100"
4,Sonoma,Zinfandel,Red,2016,"5,070.5",20.0,"5,090.5","15,287.7","$2,840.06","$43,418,000"
5,Sonoma,Zinfandel,Red,2015,"4,988.3",85.1,"5,073.4","13,070.9","$2,711.07","$35,436,200"
6,Sonoma,Merlot,Red,2016,"4,115.7",24.6,"4,140.3","13,761.0","$1,818.10","$25,018,900"
7,Sonoma,Merlot,Red,2015,"4,108.2",43.4,"4,151.6","12,031.4","$1,717.25","$20,661,000"
8,Sonoma,Syrah-Shiraz,Red,2016,"1,575.6",13.5,"1,589.1","3,618.1","$2,596.01","$9,392,600"
9,Sonoma,Syrah-Shiraz,Red,2015,"1,569.8",15.5,"1,585.3","2,848.1","$2,525.16","$7,192,000"
10,Sonoma,Petite Sirah,Red,2016,694.5,4.2,698.7,"3,266.3","$2,797.89","$9,138,700"
11,Sonoma,Petite Sirah,Red,2015,645.6,50.4,696.0,"2,347.4","$2,715.79","$6,375,100"
12,Sonoma,Malbec,Red,2016,551.5,4.7,556.2,"2,960.5","$2,629.78","$7,785,500"
13,Sonoma,Malbec,Red,2015,540.5,12.9,553.4,"1,896.3","$2,636.24","$4,999,200"
14,Sonoma,Cabernet Franc,Red,2016,578.5,28.5,607.0,"1,382.5","$2,955.14","$4,085,500"
15,Sonoma,Cabernet Franc,Red,2015,569.9,34.3,604.2,"1,357.8","$2,794.59","$3,794,400"
16,Sonoma,Petit Verdot,Red,2016,278.3,16.5,294.8,"1,332.0","$2,976.71","$3,965,000"
17,Sonoma,Petit Verdot,Red,2015,266.2,25.7,291.9,953.4,"$2,719.87","$2,593,200"
18,Sonoma,Sangiovese,Red,2016,316.9,0.0,316.9,"1,091.1","$2,314.48","$2,525,300"
19,Sonoma,Sangiovese,Red,2015,211.3,0.0,211.3,929.3,"$2,244.27","$2,085,700"
20,Sonoma,Grenache,Red,2016,152.7,3.6,156.3,739.7,"$2,995.16","$2,215,500"
21,Sonoma,Grenache,Red,2015,146.4,3.7,150.1,567.4,"$2,901.69","$1,646,500"
22,Sonoma,Mataro/Mouvedere,Red,2016,41.6,0.9,42.5,771.5,"$2,119.36","$1,635,100"
23,Sonoma,Mataro/Mouvedere,Red,2015,0.0,0.0,0.0,149.7,"$3,082.19","$461,400"
24,Sonoma,TOTAL ALL REDS,Red,2016,"39,821.4","1,342.0","41,163.5","130,589.3","$3,008.75","$392,910,600"
25,Sonoma,TOTAL ALL REDS,Red,2015,"38,917.8","2,679.1","41,596.9","101,800.1","$2,819.84","$287,060,000"

number of row for year 2015 table is: 26

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2015,569.9,34.3,604.1,"1,357.8","$2,794.59","$3,794,400"
1,Sonoma,Cabernet Franc,Red,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
2,Sonoma,Cabernet Sauvignon,Red,2015,"11,808.8","1,014.7","12,823.4","32,947.3","$2,724.17","$89,754,100"
3,Sonoma,Cabernet Sauvignon,Red,2014,"11,689.7","1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
4,Sonoma,Carignane,Red,2015,162.7,0.0,162.7,305.8,"$2,195.62","$671,500"
5,Sonoma,Carignane,Red,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
6,Sonoma,Grenache,Red,2015,146.4,3.7,150.1,567.4,"$2,901.69","$1,646,500"
7,Sonoma,Grenache,Red,2014,119.3,5.2,124.5,701.7,"$2,830.53","$1,986,200"
8,Sonoma,Malbec,Red,2015,540.5,12.9,553.4,"1,896.3","$2,636.24","$4,999,200"
9,Sonoma,Malbec,Red,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
10,Sonoma,Merlot,Red,2015,"4,108.2",43.4,"4,151.6","12,031.4","$1,717.25","$20,661,000"
11,Sonoma,Merlot,Red,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"
12,Sonoma,Petite Sirah,Red,2015,645.6,50.4,696.0,"2,347.4","$2,715.79","$6,375,100"
13,Sonoma,Petite Sirah,Red,2014,630.1,55.1,685.2,"2,873.5","$2,548.12","$7,332,100"
14,Sonoma,Petite Verdot,Red,2015,266.2,25.7,292.0,953.4,"$2,719.87","$2,593,200"
15,Sonoma,Petite Verdot,Red,2014,250.0,34.2,284.2,"1,251.1","$2,667.28","$3,337,100"
16,Sonoma,Pinot Noir,Red,2015,"12,850.8",750.0,"13,600.7","30,667.2","$3,525.42","$108,114,800"
17,Sonoma,Pinot Noir,Red,2014,"12,567.9","1,014.4","13,582.7","47,677.2","$3,251.49","$155,022,000"
18,Sonoma,Sangiovese,Red,2015,211.3,0.0,211.3,929.3,"$2,244.27","$2,085,700"
19,Sonoma,Sangiovese,Red,2014,210.2,0.0,210.3,"1,211.9","$2,352.94","$2,851,600"
20,Sonoma,Syrah-Shiraz,Red,2015,"1,569.8",15.5,"1,585.3","2,848.1","$2,525.16","$7,192,000"
21,Sonoma,Syrah-Shiraz,Red,2014,"1,649.5",9.8,"1,659.3","4,642.6","$2,314.44","$10,745,100"
22,Sonoma,Zinfandel,Red,2015,"4,988.3",85.1,"5,073.4","13,070.9","$2,711.07","$35,436,200"
23,Sonoma,Zinfandel,Red,2014,"5,015.8",112.1,"5,127.9","15,597.2","$2,543.78","$39,675,900"
24,Sonoma,TOTAL ALL REDS,Red,2015,"38,917.8","2,679.1","41,596.9","101,800.1","$2,819.84","$287,060,000"
25,Sonoma,TOTAL ALL REDS,Red,2014,"38,775.8","3,037.2","41,813.0","144,021.5","$2,685.05","$386,705,000"

number of row for year 2014 table is: 26

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
1,Sonoma,Cabernet Franc,Red,2013,604.5,13.2,617.7,"1,917.8","$2,445.23","$4,689,500"
2,Sonoma,Cabernet Sauvignon,Red,2014,"11,689.7","1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
3,Sonoma,Cabernet Sauvignon,Red,2013,"11,830.3","1,070.8","12,901.1","44,255.8","$2,462.99","$109,001,600"
4,Sonoma,Carignane,Red,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
5,Sonoma,Carignane,Red,2013,579.6,4.0,583.6,506.7,"$1,870.18","$947,700"
6,Sonoma,Malbec,Red,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
7,Sonoma,Malbec,Red,2013,425.7,109.4,535.1,"2,706.6","$2,356.19","$6,377,300"
8,Sonoma,Merlot,Red,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"
9,Sonoma,Merlot,Red,2013,"4,619.9",27.3,"4,647.2","18,784.5","$1,607.03","$30,187,300"
10,Sonoma,Meunier,Red,2014,88.8,6.6,95.4,607.6,"$2,305.57","$1,400,900"
11,Sonoma,Meunier,Red,2013,91.8,6.6,98.4,716.9,"$2,285.40","$1,638,500"
12,Sonoma,Petite Sirah,Red,2014,630.1,55.1,685.2,"2,873.5","$2,548.12","$7,322,100"
13,Sonoma,Petite Sirah,Red,2013,598.3,83.5,681.8,"2,856.8","$2,477.06","$7,076,500"
14,Sonoma,Petite Verdot,Red,2014,250.0,34.2,284.2,"1,251.1","$2,667.28","$3,337,100"
15,Sonoma,Petite Verdot,Red,2013,236.9,30.5,267.4,"1,120.0","$2,840.39","$3,181,300"
16,Sonoma,Pinot Noir,Red,2014,"12,567.9","1,014.4","13,582.3","47,677.2","$3,251.49","$155,022,000"
17,Sonoma,Pinot Noir,Red,2013,"12,539.3",948.1,"13,487.4","54,826.8","$3,079.99","$168,866,000"
18,Sonoma,Sangiovese,Red,2014,210.2,0.0,210.2,"1,211.9","$2,352.94","$2,851,600"
19,Sonoma,Sangiovese,Red,2013,195.9,12.7,208.6,"1,141.1","$2,383.10","$2,719,400"
20,Sonoma,Syrah-Shiraz,Red,2014,"1,649.5",9.8,"1,659.3","4,642.6","$2,314.44","$10,745,100"
21,Sonoma,Syrah-Shiraz,Red,2013,"1,731.9",7.0,"1,738.9","4,835.8","$2,246.05","$10,861,500"
22,Sonoma,Zinfandel,Red,2014,"5,015.8",112.1,"5,127.9","15,597.2","$2,543.78","$39,675,900"
23,Sonoma,Zinfandel,Red,2013,"5,139.0",159.8,"5,298.8","20,172.3","$2,444.51","$49,311,400"
24,Sonoma,TOTAL ALL REDS,Red,2014,"38,775.8","3,037.2","41,813.0","144,021.5","$2,685.05","$386,705,000"
25,Sonoma,TOTAL ALL REDS,Red,2013,"39,788.7","3,167.3","42,956.0","156,435.3","$2,558.50","$400,239,800"

number of row for year 2011 table is: 26

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2011,655.9,6.7,662.6,"1,568.6","$2,209.15","$3,465,300"
1,Sonoma,Cabernet Franc,Red,2010,653.9,14.3,668.2,"1,436.3","$2,166.55","$3,111,900"
2,Sonoma,Cabernet Sauvignon,Red,2011,"11,726.8",291.5,"12,018.3","33,126.8","$2,111.24","$69,938,700"
3,Sonoma,Cabernet Sauvignon,Red,2010,"11,549.0",468.3,"12,017.3","37,933.3","$2,083.96","$79,051,500"
4,Sonoma,Carignane,Red,2011,615.4,0.0,615.4,373.2,"$2,019.14","$753,600"
5,Sonoma,Carignane,Red,2010,180.3,1.0,181.3,270.4,"$1,949.11","$527,100"
6,Sonoma,Malbec,Red,2011,322.4,76.6,399.0,"1,110.5","$2,340.51","$2,599,200"
7,Sonoma,Malbec,Red,2010,310.4,69.1,379.5,770.5,"$2,430.83","$1,873,000"
8,Sonoma,Merlot,Red,2011,"5,126.6",23.4,"5,149.9","14,670.5","$1,380.85","$20,257,800"
9,Sonoma,Merlot,Red,2010,"5,248.0",55.6,"5,303.6","17,440.9","$1,297.08","$22,622,300"
10,Sonoma,Meunier,Red,2011,108.5,15.0,123.5,301.4,"$2,698.80","$813,500"
11,Sonoma,Meunier,Red,2010,108.5,15.0,123.5,406.5,"$2,928.56","$1,190,500"
12,Sonoma,Petite Sirah,Red,2011,575.0,22.2,597.1,"2,521.1","$2,325.25","$5,862,200"
13,Sonoma,Petite Sirah,Red,2010,522.6,37.7,560.3,"2,085.9","$2,377.94","$4,960,200"
14,Sonoma,Petite Verdot,Red,2011,209.2,2.6,211.8,851.7,"$2,461.02","$2,096,100"
15,Sonoma,Petite Verdot,Red,2010,202.9,9.2,212.1,695.5,"$2,476.49","$1,722,400"
16,Sonoma,Pinot Noir,Red,2011,"11,862.6",377.1,"12,239.7","28,350.2","$2,902.47","$82,285,700"
17,Sonoma,Pinot Noir,Red,2010,"11,456.0",675.5,"12,131.5","29,791.3","$2,825.12","$84,164,000"
18,Sonoma,Sangiovese,Red,2011,89.5,36.5,126.0,845.2,"$2,204.51","$1,863,300"
19,Sonoma,Sangiovese,Red,2010,259.7,48.4,308.1,983.6,"$2,244.09","$2,207,300"
20,Sonoma,Syrah-Shiraz,Red,2011,"1,773.1",19.1,"1,792.3","3,614.0","$2,124.31","$7,677,300"
21,Sonoma,Syrah-Shiraz,Red,2010,"1,791.6",51.7,"1,843.3","4,587.6","$2,030.22","$9,313,900"
22,Sonoma,Zinfandel,Red,2011,"5,216.8",81.1,"5,297.9","13,101.0","$2,357.61","$30,887,100"
23,Sonoma,Zinfandel,Red,2010,"5,055.0",112.5,"5,167.5","10,864.4","$2,260.27","$24,556,500"
24,Sonoma,TOTAL ALL REDS,Red,2011,"38,281.7",951.7,"39,233.4","101,818.5","$2,301.97","$234,383,132"
25,Sonoma,TOTAL ALL REDS,Red,2010,"37,337.9",1558.3,"38,896.1","108,497.4","$2,211.08","$239,896,431"

number of row for year 2010 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2010,653.9,14.3,668.2,"1,436.3","$2,166.55","$3,111,900"
1,Sonoma,Cabernet Franc,Red,2009,657.9,48.8,706.7,"1,935.6","$2,358.82","$4,565,800"
2,Sonoma,Cabernet Sauvignon,Red,2010,"11,549.0",468.3,"12,017.3","37,933.3","$2,083.96","$79,051,500"
3,Sonoma,Cabernet Sauvignon,Red,2009,"11,658.5",730.5,"12,389.0","41,140.6","$2,280.67","$93,828,200"
4,Sonoma,Carignane,Red,2010,180.3,1.0,181.3,270.4,"$1,949.11","$527,100"
5,Sonoma,Carignane,Red,2009,182.0,2.8,184.8,464.2,"$1,919.43","$891,000"
6,Sonoma,Malbec,Red,2010,310.4,69.1,379.5,770.5,"$2,430.83","$1,873,000"
7,Sonoma,Malbec,Red,2009,281.8,82.1,363.9,877.9,"$2,491.49","$2,187,300"
8,Sonoma,Merlot,Red,2010,"5,248.0",55.6,"5,303.6","17,440.9","$1,297.08","$22,622,300"
9,Sonoma,Merlot,Red,2009,"5,736.9",109.1,"5,846.0","16,506.5","$1,507.00","$24,875,300"
10,Sonoma,Meunier,Red,2010,108.5,15.0,123.5,406.5,"$2,928.56","$1,190,500"
11,Sonoma,Meunier,Red,2009,109.0,15.0,124.0,398.5,"$3,056.21","$1,217,900"
12,Sonoma,Petite Sirah,Red,2010,522.6,37.7,560.3,"2,085.9","$2,377.94","$4,960,200"
13,Sonoma,Petite Sirah,Red,2009,503.9,85.9,589.8,"2,300.6","$2,480.13","$5,705,800"
14,Sonoma,Petite Verdot,Red,2010,202.9,9.2,212.1,695.5,"$2,476.49","$1,722,400"
15,Sonoma,Petite Verdot,Red,2009,189.0,34.8,223.8,918.9,"$2,778.24","$2,553,000"
16,Sonoma,Pinot Noir,Red,2010,"11,456.0",675.5,"12,131.5","29,791.3","$2,825.12","$84,164,000"
17,Sonoma,Pinot Noir,Red,2009,"10,746.2","1,988.5","12,734.7","31,961.2","$3,043.08","$97,260,500"
18,Sonoma,Sangiovese,Red,2010,259.7,48.4,308.1,983.6,"$2,244.09","$2,207,300"
19,Sonoma,Sangiovese,Red,2009,298.6,11.1,309.7,"1,210.6","$2,231.17","$2,701,100"
20,Sonoma,Syrah-Shiraz,Red,2010,"1,791.6",51.7,"1,843.3","4,587.6","$2,030.22","$9,313,900"
21,Sonoma,Syrah-Shiraz,Red,2009,"1,816.6",168.5,"1,985.1","5,563.3","$2,314.65","$12,877,100"
22,Sonoma,Zinfandel,Red,2010,"5,055.0",112.5,"5,167.5","10,864.4","$2,260.27","$24,556,500"
23,Sonoma,Zinfandel,Red,2009,"5,229.7",171.5,"5,401.2","15,637.4","$2,462.39","$38,505,400"
24,Sonoma,Other Reds,Red,2010,466.6,48.0,514.6,"1,214.8",$0.0,"$9,416,500"
25,Sonoma,Other Reds,Red,2009,527.2,187.6,714.8,"1,839.7",$0.0,"$6,180,000"
26,Sonoma,TOTAL ALL REDS,Red,2010,"37,804.4","1,606.3","39,410.7","108,481.0","$2,255.85","$244,717,100"
27,Sonoma,TOTAL ALL REDS,Red,2009,"37,937.2","3,636.2","41,573.4","120,717.0","$2,430.05","$293,348,400"

number of row for year 2009 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2009,657.9,48.8,706.7,"1,935.6","$2,358.82","$4,565,800"
1,Sonoma,Cabernet Franc,Red,2008,638.7,49.9,688.6,"1,594.8","$2,338.83","$3,730,000"
2,Sonoma,Cabernet Sauvignon,Red,2009,"11,658.5",730.5,"12,389.0","41,140.6","$2,280.67","$93,828,200"
3,Sonoma,Cabernet Sauvignon,Red,2008,"11,576.0",678.4,"12,254.4","31,870.8","$2,321.51","$73,988,400"
4,Sonoma,Carignane,Red,2009,182.0,2.8,184.8,464.2,"$1,919.43","$891,000"
5,Sonoma,Carignane,Red,2008,181.1,0.0,181.1,327.7,"$1,944.90","$637,400"
6,Sonoma,Malbec,Red,2009,281.8,82.1,363.9,877.9,"$2,491.49","$2,187,300"
7,Sonoma,Malbec,Red,2008,272.0,76.0,348.0,787.6,"$2,550.60","$2,008,900"
8,Sonoma,Merlot,Red,2009,"5,736.9",109.1,"5,846.0","16,506.5","$1,507.00","$24,875,300"
9,Sonoma,Merlot,Red,2008,"5,875.6",133.4,"6,009.0","13,298.5","$1,555.48","$20,685,600"
10,Sonoma,Meunier,Red,2009,109.0,15.0,124.0,398.5,"$3,056.21","$1,217,900"
11,Sonoma,Meunier,Red,2008,105.9,4.5,110.4,325.2,"$2,769.47","$900,700"
12,Sonoma,Petite Sirah,Red,2009,503.9,85.9,589.8,"2,300.6","$2,480.13","$5,705,800"
13,Sonoma,Petite Sirah,Red,2008,466.4,98.1,564.5,"1,905.9","$2,535.97","$4,833,400"
14,Sonoma,Petite Verdot,Red,2009,189.0,34.8,223.8,918.9,"$2,778.24","$2,553,000"
15,Sonoma,Petite Verdot,Red,2008,174.4,45.1,219.5,650.3,"$2,707.89","$1,761,000"
16,Sonoma,Pinot Noir,Red,2009,"10,746.2","1,988.5","12,734.7","31,961.2","$3,043.08","$97,260,500"
17,Sonoma,Pinot Noir,Red,2008,"10,293.2","2,242.5","12,535.7","29,441.5","$3,170.71","$93,350,500"
18,Sonoma,Sangiovese,Red,2009,298.6,11.1,309.7,"1,210.6","$2,231.17","$2,701,100"
19,Sonoma,Sangiovese,Red,2008,277.6,14.9,292.5,716.8,"$2,226.54","$1,596,000"
20,Sonoma,Syrah-Shiraz,Red,2009,"1,816.6",168.5,"1,985.1","5,563.3","$2,314.65","$12,877,100"
21,Sonoma,Syrah-Shiraz,Red,2008,"1,770.6",216.4,"1,987.0","4,789.9","$2,331.26","$11,166,600"
22,Sonoma,Zinfandel,Red,2009,"5,229.7",171.5,"5,401.2","15,637.4","$2,462.39","$38,505,400"
23,Sonoma,Zinfandel,Red,2008,"5,384.5",237.1,"5,621.6","12,190.6","$2,485.66","$30,301,700"
24,Sonoma,Other Reds,Red,2009,527.2,187.6,714.8,"1,839.7",$0.0,"$6,180,000"
25,Sonoma,Other Reds,Red,2008,512.7,80.7,593.4,"1,528.8",$0.0,"$2,476,400"
26,Sonoma,TOTAL ALL REDS,Red,2009,"37,937.2","3,636.2","41,573.4","120,717.0","$2,430.05","$293,348,400"
27,Sonoma,TOTAL ALL REDS,Red,2008,"37,528.7","3,877.0","41,405.7","99,428.4","$2,488.59","$247,436,600"

number of row for year 2008 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2008,638.7,49.9,688.6,"1,594.8","$2,338.83","$3,730,000"
1,Sonoma,Cabernet Franc,Red,2007,635.6,58.8,694.4,"2,066.5","$2,097.15","$4,333,800"
2,Sonoma,Cabernet Sauvignon,Red,2008,"11,576.0",678.4,"12,254.4","31,870.8","$2,321.51","$73,988,400"
3,Sonoma,Cabernet Sauvignon,Red,2007,"11,405.0",688.7,"12,093.7","41,550.6","$2,237.73","$92,979,100"
4,Sonoma,Carignane,Red,2008,181.1,0.0,181.1,327.7,"$1,944.90","$637,400"
5,Sonoma,Carignane,Red,2007,180.5,0.6,181.1,384.6,"$1,861.81","$716,100"
6,Sonoma,Malbec,Red,2008,272.0,76.0,348.0,787.6,"$2,550.60","$2,008,900"
7,Sonoma,Malbec,Red,2007,252.7,77.3,330.0,837.2,"$2,487.87","$2,082,900"
8,Sonoma,Merlot,Red,2008,"5,875.6",133.4,"6,009.0","13,298.5","$1,555.48","$20,685,600"
9,Sonoma,Merlot,Red,2007,"6,206.6",211.8,"6,418.4","21,337.4","$1,452.25","$30,987,300"
10,Sonoma,Meunier,Red,2008,105.9,4.5,110.4,325.2,"$2,769.47","$900,700"
11,Sonoma,Meunier,Red,2007,114.4,1.5,115.9,416.7,"$2,476.94","$1,032,200"
12,Sonoma,Petite Sirah,Red,2008,466.4,98.1,564.5,"1,905.9","$2,535.97","$4,833,400"
13,Sonoma,Petite Sirah,Red,2007,444.7,101.7,546.4,"2,320.1","$2,428.79","$5,635,100"
14,Sonoma,Petite Verdot,Red,2008,174.4,45.1,219.5,650.3,"$2,707.89","$1,761,000"
15,Sonoma,Petite Verdot,Red,2007,164.8,52.3,217.1,704.9,"$2,688.20","$1,895,000"
16,Sonoma,Pinot Noir,Red,2008,"10,293.2","2,242.5","12,535.7","29,441.5","$3,170.71","$93,350,500"
17,Sonoma,Pinot Noir,Red,2007,"10,198.1","1,612.3","11,810.3","29,486.9","$2,831.16","$83,482,200"
18,Sonoma,Sangiovese,Red,2008,277.6,14.9,292.5,716.8,"$2,226.54","$1,596,000"
19,Sonoma,Sangiovese,Red,2007,275.7,13.9,289.6,937.5,"$2,008.00","$1,882,500"
20,Sonoma,Syrah-Shiraz,Red,2008,"1,770.6",216.4,"1,987.0","4,789.9","$2,331.26","$11,166,600"
21,Sonoma,Syrah-Shiraz,Red,2007,"1,749.4",206.0,"1,955.4","7,860.4","$2,233.46","$17,555,900"
22,Sonoma,Zinfandel,Red,2008,"5,384.5",237.1,"5,621.6","12,190.6","$2,485.66","$30,301,700"
23,Sonoma,Zinfandel,Red,2007,"5,211.9",244.3,"5,456.2","14,591.5","$2,376.30","$34,673,800"
24,Sonoma,Other Reds,Red,2008,512.7,80.7,593.4,"1,5828.8","$1,619.83","$2,476,400"
25,Sonoma,Other Reds,Red,2007,483.9,143.7,627.6,"1,754.6","$2,986.55","$5,240,200"
26,Sonoma,TOTAL ALL REDS,Red,2008,"37,528.7","3,877.0","41,405.7","99,428.4","$2,488.59","$247,436,600"
27,Sonoma,TOTAL ALL REDS,Red,2007,"37,323.3","3,412.8","40,736.1","124,248.9","$2,273.63","$282,496,100"

number of row for year 2007 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2007,635.6,58.8,694.4,"2,066.5","$2,097.15","$4,333,800"
1,Sonoma,Cabernet Franc,Red,2006,679.1,59.2,738.9,"1,664.9","$2,395.21","$3,987,700"
2,Sonoma,Cabernet Sauvignon,Red,2007,"11,405.0",688.7,"12,093.7","41,550.6","$2,237.73","$92,979,100"
3,Sonoma,Cabernet Sauvignon,Red,2006,"11,527.2",547.4,"12,074.6","38,410.3","$2,265.69","$87,025,900"
4,Sonoma,Carignane,Red,2007,180.5,0.6,181.1,384.6,"$1,861.81","$716,100"
5,Sonoma,Carignane,Red,2006,188.0,1.6,189.6,394.4,"$1,804.52","$711,800"
6,Sonoma,Malbec,Red,2007,252.7,77.3,330.0,837.2,"$2,487.87","$2,082,900"
7,Sonoma,Malbec,Red,2006,241.1,43.3,284.4,"1,393.0","$2,483.61","$3,459,700"
8,Sonoma,Merlot,Red,2007,"6,206.6",211.8,"6,418.4","21,337.4","$1,452.25","$30,987,300"
9,Sonoma,Merlot,Red,2006,"6,697.4",197.5,"6,894.9","26,015.2","$1,529.52","$39,790,800"
10,Sonoma,Meunier,Red,2007,114.4,1.5,115.9,416.7,"$2,476.94","$1,032,200"
11,Sonoma,Meunier,Red,2006,103.0,3.0,106.0,682.8,"$2,166.97","$1,479,700"
12,Sonoma,Petite Sirah,Red,2007,444.7,101.7,546.4,"2,320.1","$2,428.79","$5,635,100"
13,Sonoma,Petite Sirah,Red,2006,417.3,65.7,483.0,"1,708.7","$2,371.27","$4,051,800"
14,Sonoma,Petite Verdot,Red,2007,164.8,52.3,217.1,704.9,"$2,688.20","$1,895,000"
15,Sonoma,Petite Verdot,Red,2006,167.9,44.7,212.6,651.2,"$2,677.21","$1,743,400"
16,Sonoma,Pinot Noir,Red,2007,"10,198.1","1,612.3","11,810.3","29,486.9","$2,831.16","$83,482,200"
17,Sonoma,Pinot Noir,Red,2006,"9,884.7","1,146.2","11,030.9","38,453.8","$2,507.31","$96,415,600"
18,Sonoma,Sangiovese,Red,2007,275.7,13.9,289.6,937.5,"$2,008.00","$1,882,500"
19,Sonoma,Sangiovese,Red,2006,288.5,6.8,295.3,"1,275.1","$1,924.10","$2,453,500"
20,Sonoma,Syrah-Shiraz,Red,2007,"1,749.4",206.0,"1,955.4","7,860.4","$2,233.46","$17,555,900"
21,Sonoma,Syrah-Shiraz,Red,2006,"1,804.9",129.1,"1,934.0","6,844.1","$2,231.25","$15,270,900"
22,Sonoma,Zinfandel,Red,2007,"5,211.9",244.3,"5,456.2","14,591.5","$2,376.30","$34,673,800"
23,Sonoma,Zinfandel,Red,2006,"5,433.0",236.4,"5,669.4","16,683.7","$2,309.13","$38,524,900"
24,Sonoma,Other Reds,Red,2007,483.9,143.7,627.6,"1,754.6","$2,986.55","$5,240,200"
25,Sonoma,Other Reds,Red,2006,517.5,37.3,554.8,"1,469.6","$2,110.57","$3,101,700"
26,Sonoma,TOTAL ALL REDS,Red,2007,"37,323.3","3,412.8","40,736.1","124,248.9","$2,273.63","$282,496,100"
27,Sonoma,TOTAL ALL REDS,Red,2006,"37,950.2","2,518.2","40,468.4","135,646.8","$2,197.01","$298,017,400"

number of row for year 2006 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2006,679.7,59.2,738.9,"1,664.9","$2,395.21","$3,987,800"
1,Sonoma,Cabernet Franc,Red,2005,673.1,64.8,737.9,"2,318.8","$2,506.83","$5,812,900"
2,Sonoma,Cabernet Sauvignon,Red,2006,"11,527.2",547.4,"12,074.6","38,410.3","$2,265.69","$87,025,900"
3,Sonoma,Cabernet Sauvignon,Red,2005,"11,404.7",875.4,"12,280.1","45,577.2","$2,305.27","$105,067,800"
4,Sonoma,Carignane,Red,2006,188.0,1.6,189.6,394.4,"$1,804.52","$711,800"
5,Sonoma,Carignane,Red,2005,181.8,8.8,190.6,440.6,"$1,888.61","$832,200"
6,Sonoma,Malbec,Red,2006,241.1,43.3,284.4,"1,393.0","$2,483.61","$3,459,700"
7,Sonoma,Malbec,Red,2005,234.1,36.1,270.2,731.8,"$2,496.31","$1,826,800"
8,Sonoma,Merlot,Red,2006,"6,697.4",197.5,"6,894.9","26,015.2","$1,529.52","$39,790,800"
9,Sonoma,Merlot,Red,2005,"6,971.9",315.6,"7,287.6","31,656.3","$1,591.72","$50,388,000"
10,Sonoma,Meunier,Red,2006,103.0,3.0,106.0,682.8,"$2,166.97","$1,479,700"
11,Sonoma,Meunier,Red,2005,109.0,13.0,122.0,332.2,"$1,991.00","$661,500"
12,Sonoma,Petite Sirah,Red,2006,417.3,65.7,483.0,"1,708.7","$2,371.27","$4,051,800"
13,Sonoma,Petite Sirah,Red,2005,391.2,63.4,454.6,"2,125.4","$2,293.95","$4,875,600"
14,Sonoma,Petite Verdot,Red,2006,167.9,44.7,212.6,651.2,"$2,677.21","$1,743,400"
15,Sonoma,Petite Verdot,Red,2005,155.5,18.4,173.8,634.6,"$2,608.88","$1,655,600"
16,Sonoma,Pinot Noir,Red,2006,"9,884.7","1,146.2","11,030.9","38,453.8","$2,507.31","$96,415,600"
17,Sonoma,Pinot Noir,Red,2005,"9,247.2","1,228.9","10,476.1","26,944.3","$2,128.99","$57,364,200"
18,Sonoma,Sangiovese,Red,2006,288.5,6.8,295.3,"1,275.1","$1,924.10","$2,453,500"
19,Sonoma,Sangiovese,Red,2005,300.4,6.8,307.2,"1,528.5","$1,797.84","$2,748,000"
20,Sonoma,Syrah-Shiraz,Red,2006,"1,804.9",129.1,"1,934.0","6,844.1","$2,231.25","$15,270,900"
21,Sonoma,Syrah-Shiraz,Red,2005,"1,594.9",268.9,"1,863.8","7,959.4","$2,145.47","$17,076,700"
22,Sonoma,Zinfandel,Red,2006,"5,433.0",236.4,"5,669.4","16,683.7","$2,309.13","$38,524,900"
23,Sonoma,Zinfandel,Red,2005,"5,044.2",504.8,"5,549.0","17,866.5","$2,306.54","$41,209,800"
24,Sonoma,Other Reds,Red,2006,517.5,37.3,554.8,"1,469.6","$2,110.57","$3,101,700"
25,Sonoma,Other Reds,Red,2005,586.7,48.0,634.7,"1,827.6","$1,260.29","$2,303,300"
26,Sonoma,TOTAL ALL REDS,Red,2006,"37,950.2","2,518.2","40,468.4","135,646.8","$2,197.01","$298,017,400"
27,Sonoma,TOTAL ALL REDS,Red,2005,"36,894.7","3,453.0*","40,347.6","139,943.2","$2,085.72","$291,882,400"

number of row for year 2005 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2005,701.4,64.8,766.2,"2,318.8","$2,506.83","$5,812,900"
1,Sonoma,Cabernet Franc,Red,2004,603.1,87.2,690.2,"1,692.1","$2,498.88","$4,228,400"
2,Sonoma,Cabernet Sauvigno,Red,2005,"11,791.6",875.4,"12,667.0","45,577.2","$2,305.27","$105,067,800"
3,Sonoma,Cabernet Sauvigno,Red,2004,"10,216.0","1,910.2","12,126.2","30,561.3","$2,397.71","$73,277,200"
4,Sonoma,Carignane,Red,2005,189.3,8.8,198.1,440.6,"$1,888.61","$832,200"
5,Sonoma,Carignane,Red,2004,185.7,9.1,194.8,418.9,"$1,477.99","$619,200"
6,Sonoma,Malbec,Red,2005,249.3,36.1,285.4,731.8,"$2,496.31","$1,826,800"
7,Sonoma,Malbec,Red,2004,206.5,67.0,273.5,430.5,"$2,419.96","$1,041,800"
8,Sonoma,Merlot,Red,2005,"7,137.8",315.6,"7,453.4","31,656.3","$1,591.72","$50,388,000"
9,Sonoma,Merlot,Red,2004,"6,873.0",518.4,"7,391.4","22,855.2","$1,663.90","$38,028,800"
10,Sonoma,Meunier,Red,2005,119.0,13.0,132.0,332.2,"$1,991.00","$661,500"
11,Sonoma,Meunier,Red,2004,109.0,14.0,123.0,471.3,"$1,951.39","$919,700"
12,Sonoma,Petite Sirah,Red,2005,418.1,63.4,481.5,"2,125.4","$2,293.95","$4,875,600"
13,Sonoma,Petite Sirah,Red,2004,356.0,93.0,449.0,"1,256.0","$2,445.12","$3,071,100"
14,Sonoma,Petite Verdot,Red,2005,162.8,18.4,181.2,634.6,"$2,608.88","$1,655,600"
15,Sonoma,Petite Verdot,Red,2004,134.6,37.1,171.6,444.8,"$2,685.95","$1,194,800"
16,Sonoma,Pinot Noir,Red,2005,"9,887.7","1,228.9","11,116.6","26,944.3","$2,128.99","$57,364,200"
17,Sonoma,Pinot Noir,Red,2004,"8,061.6","2,074.9","10,136.5","22,672.7","$1,974.75","$44,773,000"
18,Sonoma,Sangiovese,Red,2005,318.4,6.8,325.2,"1,528.5","$1,797.84","$2,748,000"
19,Sonoma,Sangiovese,Red,2004,336.1,33.2,369.3,"1,107.2","$2,195.35","$2,430,700"
20,Sonoma,Syrah-Shiraz,Red,2005,"1,788.7",268.9,"2,057.6","7,959.4","$2,145.47","$17,076,700"
21,Sonoma,Syrah-Shiraz,Red,2004,"1,321.7",497.9,"1,819.6","5,849.8","$2,041.91","$11,944,800"
22,Sonoma,Zinfandel,Red,2005,"5,326.6",504.8,"5,831.4","17,866.5","$2,306.54","$41,209,800"
23,Sonoma,Zinfandel,Red,2004,"4,429.3",732.6,"5,161.9","11,783.2","$2,301.63","$27,120,600"
24,Sonoma,Other Reds,Red,2005,890.6,723.5,"1,614.0","1,827.6","$1,260.29","$2,303,300"
25,Sonoma,Other Reds,Red,2004,505.3,734.6,"1,239.9","1,520.2","$2,557.90","$2,888,400"
26,Sonoma,TOTAL ALL REDS,Red,2005,"38,981.1","4,128.5","43,109.6","139,943.2","$2,085.72","$291,882,400"
27,Sonoma,TOTAL ALL REDS,Red,2004,"33,337.8","6,809.1","40,146.9","101,063.2","$2,093.13","$211,538,500"

number of row for year 2004 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2004,603.1,87.2,690.2,"1,692.1","$2,498.88","$4,228,400"
1,Sonoma,Cabernet Franc,Red,2003,612.0,75.0,687.0,"1,813.2","$2,580.74","$4,679,400"
2,Sonoma,Cabernet Sauvigno,Red,2004,"10,216.0","1,910.2","12,126.2","30,561.3","$2,397.71","$73,277,200"
3,Sonoma,Cabernet Sauvigno,Red,2003,"10,554.0","1,682.0","12,236.0","36,471.4","$2,537.94","$92,562,300"
4,Sonoma,Carignane,Red,2004,185.7,9.1,194.8,418.9,"$1,477.99","$619,200"
5,Sonoma,Carignane,Red,2003,183.0,3.1,186.1,397.5,"$1,718.81","$683,300"
6,Sonoma,Malbec,Red,2004,206.5,67.0,273.5,430.5,"$2,419.96","$1,041,800"
7,Sonoma,Malbec,Red,2003,244.9,67.0,311.9,146.7,"$2,503.24","$367,300"
8,Sonoma,Merlot,Red,2004,"6,873.0",518.4,"7,391.4","22,855.2","$1,663.90","$38,028,800"
9,Sonoma,Merlot,Red,2003,"7,027.0",402.0,"7,429.0","20,917.5","$1,768.89","$37,000,800"
10,Sonoma,Meunier,Red,2004,109.0,14.0,123.0,471.3,"$1,951.39","$919,700"
11,Sonoma,Meunier,Red,2003,109.0,13.0,122.0,572.6,"$2,060.14","$1,179,700"
12,Sonoma,Petite Sirah,Red,2004,356.0,93.0,449.0,"1,256.0","$2,445.12","$3,071,100"
13,Sonoma,Petite Sirah,Red,2003,357.0,55.0,412.0,"1,194.3","$2,503.94","$2,990,500"
14,Sonoma,Petite Verdot,Red,2004,134.6,37.1,171.6,444.8,"$2,685.95","$1,194,800"
15,Sonoma,Petite Verdot,Red,2003,144.0,31.0,175.0,400.1,"$2,676.19","$1,070,800"
16,Sonoma,Pinot Noir,Red,2004,"8,061.6","2,074.9","10,136.5","22,672.7","$1,974.75","$44,773,000"
17,Sonoma,Pinot Noir,Red,2003,"8,328.0","1,784.0","10,112.0","18,759.1","$2,011.54","$37,734,700"
18,Sonoma,Sangiovese,Red,2004,336.1,33.2,369.3,"1,107.2","$2,195.35","$2,430,700"
19,Sonoma,Sangiovese,Red,2003,407.0,33.0,440.0,"1,374.2","$2,040.91","$2,804,700"
20,Sonoma,Syrah-shiraz,Red,2004,"1,321.7",497.9,"1,819.6","5,849.8","$2,041.91","$11,944,800"
21,Sonoma,Syrah-shiraz,Red,2003,"1,359.0",433.0,"1,792.0","5,666.2","$2,060.09","$11,672,900"
22,Sonoma,Zinfandel,Red,2004,"4,429.3",732.6,"5,161.9","11,783.2","$2,301.63","$27,120,600"
23,Sonoma,Zinfandel,Red,2003,"4,504.0",607.0,"5,111.0","11,561.3","$2,334.96","$26,995,200"
24,Sonoma,Other Reds,Red,2004,505.3,734.6,"1,239.9","1,520.2","$2,557.90","$2,888,400"
25,Sonoma,Other Reds,Red,2003,816.0,718.0,"1,535.0","1,684.9","$2,152.29","$3,313,900"
26,Sonoma,TOTAL ALL REDS,Red,2004,"33,337.8","6,809.1","40,146.9","101,063.2","$2,093.13","$211,538,500"
27,Sonoma,TOTAL ALL REDS,Red,2003,"34,443.0","5,836.0","40,280.0","100,863.9","$2,211.45","$223,055,500"

number of row for year 2003 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2003,612,75,687,"1,813.20","$2,580.74","$4,679,400"
1,Sonoma,Cabernet Franc,Red,2002,560,118,678,"1,927.50","$2,532.25","$4,881,000"
2,Sonoma,Cabernet Sauvigno,Red,2003,"10,554","1,682","12,237","36,471.40","$2,537.94","$92,562,300"
3,Sonoma,Cabernet Sauvigno,Red,2002,"9,018","3,125","12,143","32,258.10","$2,694.93","$86,933,400"
4,Sonoma,Carignane,Red,2003,183,3,186,397.50,"$1,718.81","$683,300"
5,Sonoma,Carignane,Red,2002,188,3,191,498.70,"$1,562.64","$779,300"
6,Sonoma,Merlot,Red,2003,"7,027",402,"7,429","20,917.50","$1,768.89","$37,000,800"
7,Sonoma,Merlot,Red,2002,"6,698",712,"7,410","29,037.30","$1,965.47","$57,072,000"
8,Sonoma,Meunier,Red,2003,109,13,122,572.60,"$2,060.14","$1,179,700"
9,Sonoma,Meunier,Red,2002,109,3,112,426.50,"$2,164.26","$923,100"
10,Sonoma,Napa Gamay,Red,2003,42,0,42,51.60,"$1,060.86","$54,800"
11,Sonoma,Napa Gamay,Red,2002,49,0,49,93.90,"$1,089.40","$102,300"
12,Sonoma,Petite Sirah,Red,2003,357,55,412,"1,194.30","$2,503.94","$2,990,500"
13,Sonoma,Petite Sirah,Red,2002,313,83,397,"1,083.60","$2,534.18","$2,746,100"
14,Sonoma,Petite Verdot,Red,2003,144,31,175,400.10,"$2,676.19","$1,070,800"
15,Sonoma,Petite Verdot,Red,2002,87,86,174,308.80,"$2,560.45","$790,700"
16,Sonoma,Pinot Noir,Red,2003,"8,328","1,784","10,113","18,759.10","$2,011.54","$37,734,700"
17,Sonoma,Pinot Noir,Red,2002,"6,434","3,821","10,255","19,571.00","$2,131.66","$41,718,800"
18,Sonoma,Sangiovese,Red,2003,407,33,440,"1,374.20","$2,040.91","$2,804,700"
19,Sonoma,Sangiovese,Red,2002,386,66,453,"1,791.90","$2,048.31","$3,670,400"
20,Sonoma,Syrah-shiraz,Red,2003,"1,359",433,"1,792","5,666.20","$2,060.09","$11,672,900"
21,Sonoma,Syrah-shiraz,Red,2002,"1,040",717,"1,758","5,424.40","$2,254.26","$12,228,100"
22,Sonoma,Zinfandel,Red,2003,"4,504",607,"5,111","11,561.30","$2,334.96","$26,995,200"
23,Sonoma,Zinfandel,Red,2002,"4,300",828,"5,128","13,384.60","$2,494.52","$33,388,200"
24,Sonoma,Other Reds,Red,2003,816,718,"1,535","1,684.90","$2,152.29","$3,626,400"
25,Sonoma,Other Reds,Red,2002,651,832,"1,483","2,011.30","$2,436.88","$4,901,300"
26,Sonoma,Total Reds,Red,2003,"34,443","5,836","40,280","100,863.90","$2,211.45","$223,055,500"
27,Sonoma,Total Reds,Red,2002,"29,834","10,395","40,230","107,817.60","$2,319.98","$250,134,700"

number of row for year 2002 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2002,560,118,678,"1,928","$2,532.25","$4,881,000"
1,Sonoma,Cabernet Franc,Red,2001,503,137,640,"2,309","$2,424.10","$5,597,300"
2,Sonoma,Cabernet Sauvigno,Red,2002,"9,018","3,125","12,143","32,258","$2,694.93","$86,933,400"
3,Sonoma,Cabernet Sauvigno,Red,2001,"7,937","4,018","11,955","32,194","$2,698.66","$86,881,500"
4,Sonoma,Carignane,Red,2002,188,3,191,499,"$1,562.64","$779,300"
5,Sonoma,Carignane,Red,2001,182,2,184,587,"$1,529.01","$896,800"
6,Sonoma,Merlot,Red,2002,"6,698",712,"7,410","29,037","$1,965.47","$57,072,000"
7,Sonoma,Merlot,Red,2001,"6,414",962,"7,376","27,879","$2,136.86","$59,573,800"
8,Sonoma,Meunier,Red,2002,109,3,112,427,"$2,164.26","$923,100"
9,Sonoma,Meunier,Red,2001,111,3,114,566,"$1,983.57","$1,122,200"
10,Sonoma,Napa Gamay,Red,2002,49,0,49,94,"$1,089.40","$102,300"
11,Sonoma,Napa Gamay,Red,2001,91,0,91,149,"$1,289.12","$192,600"
12,Sonoma,Petite Sirah,Red,2002,313,83,397,"1,084","$2,534.18","$2,746,100"
13,Sonoma,Petite Sirah,Red,2001,293,90,383,"1,007","$2,379.44","$2,395,900"
14,Sonoma,Petite Verdot,Red,2002,87,86,174,309,"$2,560.45","$790,700"
15,Sonoma,Petite Verdot,Red,2001,78,92,171,308,"$2,408.91","$743,000"
16,Sonoma,Pinot Noir,Red,2002,"6,434","3,821","10,255","19,571","$2,131.66","$41,718,800"
17,Sonoma,Pinot Noir,Red,2001,"5,811","4,554","10,365","20,861","$2,219.03","$46,290,600"
18,Sonoma,Sangiovese,Red,2002,386,66,453,"1,792","$2,048.31","$3,670,400"
19,Sonoma,Sangiovese,Red,2001,366,70,436,"1,376","$2,020.35","$2,779,600"
20,Sonoma,Syrah-shiraz,Red,2002,"1,040",717,"1,758","5,424","$2,254.26","$12,228,100"
21,Sonoma,Syrah-shiraz,Red,2001,824,856,"1,680","4,195","$2,260.98","$9,483,700"
22,Sonoma,Zinfandel,Red,2002,"4,300",828,"5,128","13,385","$2,494.52","$33,388,200"
23,Sonoma,Zinfandel,Red,2001,"4,145",885,"5,030","14,287","$2,456.58","$35,096,500"
24,Sonoma,Other Reds,Red,2002,651,832,"1,483","2,011","$2,436.88","$4,901,300"
25,Sonoma,Other Reds,Red,2001,523,180,703,"1,995","$1,962.80","$3,914,800"
26,Sonoma,Total Reds,Red,2002,"29,834","10,395","40,230","107,818","$2,319.98","$250,134,700"
27,Sonoma,Total Reds,Red,2001,"27,279","11,848","39,127","107,712","$2,367.14","$254,968,300"

number of row for year 2001 table is: 28

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Cabernet Franc,Red,2001,503,137,640,"2,309","$2,424.10","$5,597,300"
1,Sonoma,Cabernet Franc,Red,2000,523,151,674,"2,097","$2,226.53","$4,668,600"
2,Sonoma,Cabernet Sauvigno,Red,2001,"7,937","4,018","11,955","32,194","$2,698.66","$86,881,500"
3,Sonoma,Cabernet Sauvigno,Red,2000,"7,328","3,688","11,016","32,772","$2,417.96","$79,240,400"
4,Sonoma,Carignane,Red,2001,182,2,184,587,"$1,529.01","$896,800"
5,Sonoma,Carignane,Red,2000,196,1,197,766,"$1,391.55","$1,065,400"
6,Sonoma,Merlot,Red,2001,"6,414",962,"7,376","27,879","$2,136.86","$59,573,800"
7,Sonoma,Merlot,Red,2000,"6,564","1,058","7,622","31,480","$2,019.29","$63,566,200"
8,Sonoma,Meunier,Red,2001,111,3,114,566,"$1,983.57","$1,122,200"
9,Sonoma,Meunier,Red,2000,129,17,146,637,"$2,069.27","$1,318,700"
10,Sonoma,Napa Gamay,Red,2001,91,0,91,149,"$1,289.12","$192,600"
11,Sonoma,Napa Gamay,Red,2000,84,0,84,195,"$1,143.58","$222,500"
12,Sonoma,Petite Sirah,Red,2001,293,90,383,"1,007","$2,379.44","$2,395,900"
13,Sonoma,Petite Sirah,Red,2000,280,86,366,"1,073","$2,127.81","$2,284,000"
14,Sonoma,Petite Verdot,Red,2001,78,92,171,308,"$2,408.91","$743,000"
15,Sonoma,Petite Verdot,Red,2000,86,77,163,282,"$2,176.29","$614,000"
16,Sonoma,Pinot Noir,Red,2001,"5,811","4,554","10,365","20,861","$2,219.03","$46,290,600"
17,Sonoma,Pinot Noir,Red,2000,"4,973","3,631","8,604","17,520","$2,094.39","$36,692,700"
18,Sonoma,Sangiovese,Red,2001,366,70,436,"1,376","$2,020.35","$2,779,600"
19,Sonoma,Sangiovese,Red,2000,281,68,349,"1,791","$1,859.57","$3,331,000"
20,Sonoma,Syrah-shiraz,Red,2001,824,856,"1,680","4,195","$2,260.98","$9,483,700"
21,Sonoma,Syrah-shiraz,Red,2000,559,371,930,"3,349","$2,171.65","$7,272,000"
22,Sonoma,Zinfandel,Red,2001,"4,145",885,"5,030","14,287","$2,456.58","$35,096,500"
23,Sonoma,Zinfandel,Red,2000,"4,478",665,"5,143","13,223","$2,143.10","$28,337,800"
24,Sonoma,Other Reds,Red,2001,523,180,703,"1,995","$1,962.80","$3,914,800"
25,Sonoma,Other Reds,Red,2000,455,319,774,"1,844","$2,036.69","$3,755,200"
26,Sonoma,Total Reds,Red,2001,"27,279","11,848","39,127","107,712","$2,367.14","$254,968,300"
27,Sonoma,Total Reds,Red,2000,"25,936","10,132","36,068","107,027","$2,188.11","$234,187,000"

In [7]:
sonoma_2017 = combined_data_up_to_2017.drop_duplicates().reset_index(drop=True)
sonoma_2001 = combined_data_up_to_2001.drop_duplicates().reset_index(drop=True)
sonoma_2001

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
0,Sonoma,Pinot Noir,Red,2016,"13,343.1",385.2,"13,728.3","42,566.3","$3,680.50","$156,665,300"
1,Sonoma,Pinot Noir,Red,2015,"12,850.8",750.0,"13,600.8","30,667.2","$3,525.42","$108,114,800"
2,Sonoma,Cabernet Sauvignon,Red,2016,"12,456.7",560.0,"13,016.7","41,575.7","$2,964.60","$123,255,300"
3,Sonoma,Cabernet Sauvignon,Red,2015,"11,808.8","1,014.7","12,823.5","32,947.3","$2,724.17","$89,754,100"
4,Sonoma,Zinfandel,Red,2016,"5,070.5",20.0,"5,090.5","15,287.7","$2,840.06","$43,418,000"
...,...,...,...,...,...,...,...,...,...,...
269,Sonoma,Sangiovese,Red,2000,281,68,349,"1,791","$1,859.57","$3,331,000"
270,Sonoma,Syrah-shiraz,Red,2000,559,371,930,"3,349","$2,171.65","$7,272,000"
271,Sonoma,Zinfandel,Red,2000,"4,478",665,"5,143","13,223","$2,143.10","$28,337,800"
272,Sonoma,Other Reds,Red,2000,455,319,774,"1,844","$2,036.69","$3,755,200"
273,Sonoma,Total Reds,Red,2000,"25,936","10,132","36,068","107,027","$2,188.11","$234,187,000"

In [8]:
pd.set_option('display.max_rows', 300)

In [9]:
sonoma_2001_sorted = sonoma_2001.sort_values(['Year', 'Varietal'])
sonoma_2001_sorted

,County,Varietal,Grape Color,Year,Bearing,Non-Bearing,Total,Tons,$/Ton,Total Value
260,Sonoma,Cabernet Franc,Red,2000,523,151,674,"2,097","$2,226.53","$4,668,600"
261,Sonoma,Cabernet Sauvigno,Red,2000,"7,328","3,688","11,016","32,772","$2,417.96","$79,240,400"
262,Sonoma,Carignane,Red,2000,196,1,197,766,"$1,391.55","$1,065,400"
263,Sonoma,Merlot,Red,2000,"6,564","1,058","7,622","31,480","$2,019.29","$63,566,200"
264,Sonoma,Meunier,Red,2000,129,17,146,637,"$2,069.27","$1,318,700"
265,Sonoma,Napa Gamay,Red,2000,84,0,84,195,"$1,143.58","$222,500"
272,Sonoma,Other Reds,Red,2000,455,319,774,"1,844","$2,036.69","$3,755,200"
266,Sonoma,Petite Sirah,Red,2000,280,86,366,"1,073","$2,127.81","$2,284,000"
267,Sonoma,Petite Verdot,Red,2000,86,77,163,282,"$2,176.29","$614,000"
268,Sonoma,Pinot Noir,Red,2000,"4,973","3,631","8,604","17,520","$2,094.39","$36,692,700"
269,Sonoma,Sangiovese,Red,2000,281,68,349,"1,791","$1,859.57","$3,331,000"
270,Sonoma,Syrah-shiraz,Red,2000,559,371,930,"3,349","$2,171.65","$7,272,000"
273,Sonoma,Total Reds,Red,2000,"25,936","10,132","36,068","107,027","$2,188.11","$234,187,000"
271,Sonoma,Zinfandel,Red,2000,"4,478",665,"5,143","13,223","$2,143.10","$28,337,800"
233,Sonoma,Cabernet Franc,Red,2001,503,137,640,"2,309","$2,424.10","$5,597,300"
235,Sonoma,Cabernet Sauvigno,Red,2001,"7,937","4,018","11,955","32,194","$2,698.66","$86,881,500"
237,Sonoma,Carignane,Red,2001,182,2,184,587,"$1,529.01","$896,800"
239,Sonoma,Merlot,Red,2001,"6,414",962,"7,376","27,879","$2,136.86","$59,573,800"
241,Sonoma,Meunier,Red,2001,111,3,114,566,"$1,983.57","$1,122,200"
243,Sonoma,Napa Gamay,Red,2001,91,0,91,149,"$1,289.12","$192,600"
257,Sonoma,Other Reds,Red,2001,523,180,703,"1,995","$1,962.80","$3,914,800"
245,Sonoma,Petite Sirah,Red,2001,293,90,383,"1,007","$2,379.44","$2,395,900"
247,Sonoma,Petite Verdot,Red,2001,78,92,171,308,"$2,408.91","$743,000"
249,Sonoma,Pinot Noir,Red,2001,"5,811","4,554","10,365","20,861","$2,219.03","$46,290,600"
251,Sonoma,Sangiovese,Red,2001,366,70,436,"1,376","$2,020.35","$2,779,600"
253,Sonoma,Syrah-shiraz,Red,2001,824,856,"1,680","4,195","$2,260.98","$9,483,700"
259,Sonoma,Total Reds,Red,2001,"27,279","11,848","39,127","107,712","$2,367.14","$254,968,300"
255,Sonoma,Zinfandel,Red,2001,"4,145",885,"5,030","14,287","$2,456.58","$35,096,500"
205,Sonoma,Cabernet Franc,Red,2002,560,118,678,"1,927.50","$2,532.25","$4,881,000"
232,Sonoma,Cabernet Franc,Red,2002,560,118,678,"1,928","$2,532.25","$4,881,000"
207,Sonoma,Cabernet Sauvigno,Red,2002,"9,018","3,125","12,143","32,258.10","$2,694.93","$86,933,400"
234,Sonoma,Cabernet Sauvigno,Red,2002,"9,018","3,125","12,143","32,258","$2,694.93","$86,933,400"
209,Sonoma,Carignane,Red,2002,188,3,191,498.70,"$1,562.64","$779,300"
236,Sonoma,Carignane,Red,2002,188,3,191,499,"$1,562.64","$779,300"
211,Sonoma,Merlot,Red,2002,"6,698",712,"7,410","29,037.30","$1,965.47","$57,072,000"
238,Sonoma,Merlot,Red,2002,"6,698",712,"7,410","29,037","$1,965.47","$57,072,000"
213,Sonoma,Meunier,Red,2002,109,3,112,426.50,"$2,164.26","$923,100"
240,Sonoma,Meunier,Red,2002,109,3,112,427,"$2,164.26","$923,100"
215,Sonoma,Napa Gamay,Red,2002,49,0,49,93.90,"$1,089.40","$102,300"
242,Sonoma,Napa Gamay,Red,2002,49,0,49,94,"$1,089.40","$102,300"
229,Sonoma,Other Reds,Red,2002,651,832,"1,483","2,011.30","$2,436.88","$4,901,300"
256,Sonoma,Other Reds,Red,2002,651,832,"1,483","2,011","$2,436.88","$4,901,300"
217,Sonoma,Petite Sirah,Red,2002,313,83,397,"1,083.60","$2,534.18","$2,746,100"
244,Sonoma,Petite Sirah,Red,2002,313,83,397,"1,084","$2,534.18","$2,746,100"
219,Sonoma,Petite Verdot,Red,2002,87,86,174,308.80,"$2,560.45","$790,700"
246,Sonoma,Petite Verdot,Red,2002,87,86,174,309,"$2,560.45","$790,700"
221,Sonoma,Pinot Noir,Red,2002,"6,434","3,821","10,255","19,571.00","$2,131.66","$41,718,800"
248,Sonoma,Pinot Noir,Red,2002,"6,434","3,821","10,255","19,571","$2,131.66","$41,718,800"
223,Sonoma,Sangiovese,Red,2002,386,66,453,"1,791.90","$2,048.31","$3,670,400"
250,Sonoma,Sangiovese,Red,2002,386,66,453,"1,792","$2,048.31","$3,670,400"
225,Sonoma,Syrah-shiraz,Red,2002,"1,040",717,"1,758","5,424.40","$2,254.26","$12,228,100"
252,Sonoma,Syrah-shiraz,Red,2002,"1,040",717,"1,758","5,424","$2,254.26","$12,228,100"
231,Sonoma,Total Reds,Red,2002,"29,834","10,395","40,230","107,817.60","$2,319.98","$250,134,700"
258,Sonoma,Total Reds,Red,2002,"29,834","10,395","40,230","107,818","$2,319.98","$250,134,700"
227,Sonoma,Zinfandel,Red,2002,"4,300",828,"5,128","13,384.60","$2,494.52","$33,388,200"
254,Sonoma,Zinfandel,Red,2002,"4,300",828,"5,128","13,385","$2,494.52","$33,388,200"
189,Sonoma,Cabernet Franc,Red,2003,612.0,75.0,687.0,"1,813.2","$2,580.74","$4,679,400"
204,Sonoma,Cabernet Franc,Red,2003,612,75,687,"1,813.20","$2,580.74","$4,679,400"
190,Sonoma,Cabernet Sauvigno,Red,2003,"10,554.0","1,682.0","12,236.0","36,471.4","$2,537.94","$92,562,300"
206,Sonoma,Cabernet Sauvigno,Red,2003,"10,554","1,682","12,237","36,471.40","$2,537.94","$92,562,300"
191,Sonoma,Carignane,Red,2003,183.0,3.1,186.1,397.5,"$1,718.81","$683,300"
208,Sonoma,Carignane,Red,2003,183,3,186,397.50,"$1,718.81","$683,300"
192,Sonoma,Malbec,Red,2003,244.9,67.0,311.9,146.7,"$2,503.24","$367,300"
193,Sonoma,Merlot,Red,2003,"7,027.0",402.0,"7,429.0","20,917.5","$1,768.89","$37,000,800"
210,Sonoma,Merlot,Red,2003,"7,027",402,"7,429","20,917.50","$1,768.89","$37,000,800"
194,Sonoma,Meunier,Red,2003,109.0,13.0,122.0,572.6,"$2,060.14","$1,179,700"
212,Sonoma,Meunier,Red,2003,109,13,122,572.60,"$2,060.14","$1,179,700"
214,Sonoma,Napa Gamay,Red,2003,42,0,42,51.60,"$1,060.86","$54,800"
202,Sonoma,Other Reds,Red,2003,816.0,718.0,"1,535.0","1,684.9","$2,152.29","$3,313,900"
228,Sonoma,Other Reds,Red,2003,816,718,"1,535","1,684.90","$2,152.29","$3,626,400"
195,Sonoma,Petite Sirah,Red,2003,357.0,55.0,412.0,"1,194.3","$2,503.94","$2,990,500"
216,Sonoma,Petite Sirah,Red,2003,357,55,412,"1,194.30","$2,503.94","$2,990,500"
196,Sonoma,Petite Verdot,Red,2003,144.0,31.0,175.0,400.1,"$2,676.19","$1,070,800"
218,Sonoma,Petite Verdot,Red,2003,144,31,175,400.10,"$2,676.19","$1,070,800"
197,Sonoma,Pinot Noir,Red,2003,"8,328.0","1,784.0","10,112.0","18,759.1","$2,011.54","$37,734,700"
220,Sonoma,Pinot Noir,Red,2003,"8,328","1,784","10,113","18,759.10","$2,011.54","$37,734,700"
198,Sonoma,Sangiovese,Red,2003,407.0,33.0,440.0,"1,374.2","$2,040.91","$2,804,700"
222,Sonoma,Sangiovese,Red,2003,407,33,440,"1,374.20","$2,040.91","$2,804,700"
200,Sonoma,Syrah-shiraz,Red,2003,"1,359.0",433.0,"1,792.0","5,666.2","$2,060.09","$11,672,900"
224,Sonoma,Syrah-shiraz,Red,2003,"1,359",433,"1,792","5,666.20","$2,060.09","$11,672,900"
203,Sonoma,TOTAL ALL REDS,Red,2003,"34,443.0","5,836.0","40,280.0","100,863.9","$2,211.45","$223,055,500"
230,Sonoma,Total Reds,Red,2003,"34,443","5,836","40,280","100,863.90","$2,211.45","$223,055,500"
201,Sonoma,Zinfandel,Red,2003,"4,504.0",607.0,"5,111.0","11,561.3","$2,334.96","$26,995,200"
226,Sonoma,Zinfandel,Red,2003,"4,504",607,"5,111","11,561.30","$2,334.96","$26,995,200"
162,Sonoma,Cabernet Franc,Red,2004,603.1,87.2,690.2,"1,692.1","$2,498.88","$4,228,400"
164,Sonoma,Cabernet Sauvigno,Red,2004,"10,216.0","1,910.2","12,126.2","30,561.3","$2,397.71","$73,277,200"
166,Sonoma,Carignane,Red,2004,185.7,9.1,194.8,418.9,"$1,477.99","$619,200"
168,Sonoma,Malbec,Red,2004,206.5,67.0,273.5,430.5,"$2,419.96","$1,041,800"
170,Sonoma,Merlot,Red,2004,"6,873.0",518.4,"7,391.4","22,855.2","$1,663.90","$38,028,800"
172,Sonoma,Meunier,Red,2004,109.0,14.0,123.0,471.3,"$1,951.39","$919,700"
186,Sonoma,Other Reds,Red,2004,505.3,734.6,"1,239.9","1,520.2","$2,557.90","$2,888,400"
174,Sonoma,Petite Sirah,Red,2004,356.0,93.0,449.0,"1,256.0","$2,445.12","$3,071,100"
176,Sonoma,Petite Verdot,Red,2004,134.6,37.1,171.6,444.8,"$2,685.95","$1,194,800"
178,Sonoma,Pinot Noir,Red,2004,"8,061.6","2,074.9","10,136.5","22,672.7","$1,974.75","$44,773,000"
180,Sonoma,Sangiovese,Red,2004,336.1,33.2,369.3,"1,107.2","$2,195.35","$2,430,700"
182,Sonoma,Syrah-Shiraz,Red,2004,"1,321.7",497.9,"1,819.6","5,849.8","$2,041.91","$11,944,800"
199,Sonoma,Syrah-shiraz,Red,2004,"1,321.7",497.9,"1,819.6","5,849.8","$2,041.91","$11,944,800"
188,Sonoma,TOTAL ALL REDS,Red,2004,"33,337.8","6,809.1","40,146.9","101,063.2","$2,093.13","$211,538,500"
184,Sonoma,Zinfandel,Red,2004,"4,429.3",732.6,"5,161.9","11,783.2","$2,301.63","$27,120,600"
147,Sonoma,Cabernet Franc,Red,2005,673.1,64.8,737.9,"2,318.8","$2,506.83","$5,812,900"
161,Sonoma,Cabernet Franc,Red,2005,701.4,64.8,766.2,"2,318.8","$2,506.83","$5,812,900"
163,Sonoma,Cabernet Sauvigno,Red,2005,"11,791.6",875.4,"12,667.0","45,577.2","$2,305.27","$105,067,800"
148,Sonoma,Cabernet Sauvignon,Red,2005,"11,404.7",875.4,"12,280.1","45,577.2","$2,305.27","$105,067,800"
149,Sonoma,Carignane,Red,2005,181.8,8.8,190.6,440.6,"$1,888.61","$832,200"
165,Sonoma,Carignane,Red,2005,189.3,8.8,198.1,440.6,"$1,888.61","$832,200"
150,Sonoma,Malbec,Red,2005,234.1,36.1,270.2,731.8,"$2,496.31","$1,826,800"
167,Sonoma,Malbec,Red,2005,249.3,36.1,285.4,731.8,"$2,496.31","$1,826,800"
151,Sonoma,Merlot,Red,2005,"6,971.9",315.6,"7,287.6","31,656.3","$1,591.72","$50,388,000"
169,Sonoma,Merlot,Red,2005,"7,137.8",315.6,"7,453.4","31,656.3","$1,591.72","$50,388,000"
152,Sonoma,Meunier,Red,2005,109.0,13.0,122.0,332.2,"$1,991.00","$661,500"
171,Sonoma,Meunier,Red,2005,119.0,13.0,132.0,332.2,"$1,991.00","$661,500"
159,Sonoma,Other Reds,Red,2005,586.7,48.0,634.7,"1,827.6","$1,260.29","$2,303,300"
185,Sonoma,Other Reds,Red,2005,890.6,723.5,"1,614.0","1,827.6","$1,260.29","$2,303,300"
153,Sonoma,Petite Sirah,Red,2005,391.2,63.4,454.6,"2,125.4","$2,293.95","$4,875,600"
173,Sonoma,Petite Sirah,Red,2005,418.1,63.4,481.5,"2,125.4","$2,293.95","$4,875,600"
154,Sonoma,Petite Verdot,Red,2005,155.5,18.4,173.8,634.6,"$2,608.88","$1,655,600"
175,Sonoma,Petite Verdot,Red,2005,162.8,18.4,181.2,634.6,"$2,608.88","$1,655,600"
155,Sonoma,Pinot Noir,Red,2005,"9,247.2","1,228.9","10,476.1","26,944.3","$2,128.99","$57,364,200"
177,Sonoma,Pinot Noir,Red,2005,"9,887.7","1,228.9","11,116.6","26,944.3","$2,128.99","$57,364,200"
156,Sonoma,Sangiovese,Red,2005,300.4,6.8,307.2,"1,528.5","$1,797.84","$2,748,000"
179,Sonoma,Sangiovese,Red,2005,318.4,6.8,325.2,"1,528.5","$1,797.84","$2,748,000"
157,Sonoma,Syrah-Shiraz,Red,2005,"1,594.9",268.9,"1,863.8","7,959.4","$2,145.47","$17,076,700"
181,Sonoma,Syrah-Shiraz,Red,2005,"1,788.7",268.9,"2,057.6","7,959.4","$2,145.47","$17,076,700"
160,Sonoma,TOTAL ALL REDS,Red,2005,"36,894.7","3,453.0*","40,347.6","139,943.2","$2,085.72","$291,882,400"
187,Sonoma,TOTAL ALL REDS,Red,2005,"38,981.1","4,128.5","43,109.6","139,943.2","$2,085.72","$291,882,400"
158,Sonoma,Zinfandel,Red,2005,"5,044.2",504.8,"5,549.0","17,866.5","$2,306.54","$41,209,800"
183,Sonoma,Zinfandel,Red,2005,"5,326.6",504.8,"5,831.4","17,866.5","$2,306.54","$41,209,800"
132,Sonoma,Cabernet Franc,Red,2006,679.1,59.2,738.9,"1,664.9","$2,395.21","$3,987,700"
146,Sonoma,Cabernet Franc,Red,2006,679.7,59.2,738.9,"1,664.9","$2,395.21","$3,987,800"
133,Sonoma,Cabernet Sauvignon,Red,2006,"11,527.2",547.4,"12,074.6","38,410.3","$2,265.69","$87,025,900"
134,Sonoma,Carignane,Red,2006,188.0,1.6,189.6,394.4,"$1,804.52","$711,800"
135,Sonoma,Malbec,Red,2006,241.1,43.3,284.4,"1,393.0","$2,483.61","$3,459,700"
136,Sonoma,Merlot,Red,2006,"6,697.4",197.5,"6,894.9","26,015.2","$1,529.52","$39,790,800"
137,Sonoma,Meunier,Red,2006,103.0,3.0,106.0,682.8,"$2,166.97","$1,479,700"
144,Sonoma,Other Reds,Red,2006,517.5,37.3,554.8,"1,469.6","$2,110.57","$3,101,700"
138,Sonoma,Petite Sirah,Red,2006,417.3,65.7,483.0,"1,708.7","$2,371.27","$4,051,800"
139,Sonoma,Petite Verdot,Red,2006,167.9,44.7,212.6,651.2,"$2,677.21","$1,743,400"
140,Sonoma,Pinot Noir,Red,2006,"9,884.7","1,146.2","11,030.9","38,453.8","$2,507.31","$96,415,600"
141,Sonoma,Sangiovese,Red,2006,288.5,6.8,295.3,"1,275.1","$1,924.10","$2,453,500"
142,Sonoma,Syrah-Shiraz,Red,2006,"1,804.9",129.1,"1,934.0","6,844.1","$2,231.25","$15,270,900"
145,Sonoma,TOTAL ALL REDS,Red,2006,"37,950.2","2,518.2","40,468.4","135,646.8","$2,197.01","$298,017,400"
143,Sonoma,Zinfandel,Red,2006,"5,433.0",236.4,"5,669.4","16,683.7","$2,309.13","$38,524,900"
117,Sonoma,Cabernet Franc,Red,2007,635.6,58.8,694.4,"2,066.5","$2,097.15","$4,333,800"
118,Sonoma,Cabernet Sauvignon,Red,2007,"11,405.0",688.7,"12,093.7","41,550.6","$2,237.73","$92,979,100"
119,Sonoma,Carignane,Red,2007,180.5,0.6,181.1,384.6,"$1,861.81","$716,100"
120,Sonoma,Malbec,Red,2007,252.7,77.3,330.0,837.2,"$2,487.87","$2,082,900"
121,Sonoma,Merlot,Red,2007,"6,206.6",211.8,"6,418.4","21,337.4","$1,452.25","$30,987,300"
122,Sonoma,Meunier,Red,2007,114.4,1.5,115.9,416.7,"$2,476.94","$1,032,200"
130,Sonoma,Other Reds,Red,2007,483.9,143.7,627.6,"1,754.6","$2,986.55","$5,240,200"
123,Sonoma,Petite Sirah,Red,2007,444.7,101.7,546.4,"2,320.1","$2,428.79","$5,635,100"
124,Sonoma,Petite Verdot,Red,2007,164.8,52.3,217.1,704.9,"$2,688.20","$1,895,000"
125,Sonoma,Pinot Noir,Red,2007,"10,198.1","1,612.3","11,810.3","29,486.9","$2,831.16","$83,482,200"
126,Sonoma,Sangiovese,Red,2007,275.7,13.9,289.6,937.5,"$2,008.00","$1,882,500"
127,Sonoma,Syrah-Shiraz,Red,2007,"1,749.4",206.0,"1,955.4","7,860.4","$2,233.46","$17,555,900"
131,Sonoma,TOTAL ALL REDS,Red,2007,"37,323.3","3,412.8","40,736.1","124,248.9","$2,273.63","$282,496,100"
128,Sonoma,Zinfandel,Red,2007,"5,211.9",244.3,"5,456.2","14,591.5","$2,376.30","$34,673,800"
103,Sonoma,Cabernet Franc,Red,2008,638.7,49.9,688.6,"1,594.8","$2,338.83","$3,730,000"
104,Sonoma,Cabernet Sauvignon,Red,2008,"11,576.0",678.4,"12,254.4","31,870.8","$2,321.51","$73,988,400"
105,Sonoma,Carignane,Red,2008,181.1,0.0,181.1,327.7,"$1,944.90","$637,400"
106,Sonoma,Malbec,Red,2008,272.0,76.0,348.0,787.6,"$2,550.60","$2,008,900"
107,Sonoma,Merlot,Red,2008,"5,875.6",133.4,"6,009.0","13,298.5","$1,555.48","$20,685,600"
108,Sonoma,Meunier,Red,2008,105.9,4.5,110.4,325.2,"$2,769.47","$900,700"
115,Sonoma,Other Reds,Red,2008,512.7,80.7,593.4,"1,528.8",$0.0,"$2,476,400"
129,Sonoma,Other Reds,Red,2008,512.7,80.7,593.4,"1,5828.8","$1,619.83","$2,476,400"
109,Sonoma,Petite Sirah,Red,2008,466.4,98.1,564.5,"1,905.9","$2,535.97","$4,833,400"
110,Sonoma,Petite Verdot,Red,2008,174.4,45.1,219.5,650.3,"$2,707.89","$1,761,000"
111,Sonoma,Pinot Noir,Red,2008,"10,293.2","2,242.5","12,535.7","29,441.5","$3,170.71","$93,350,500"
112,Sonoma,Sangiovese,Red,2008,277.6,14.9,292.5,716.8,"$2,226.54","$1,596,000"
113,Sonoma,Syrah-Shiraz,Red,2008,"1,770.6",216.4,"1,987.0","4,789.9","$2,331.26","$11,166,600"
116,Sonoma,TOTAL ALL REDS,Red,2008,"37,528.7","3,877.0","41,405.7","99,428.4","$2,488.59","$247,436,600"
114,Sonoma,Zinfandel,Red,2008,"5,384.5",237.1,"5,621.6","12,190.6","$2,485.66","$30,301,700"
87,Sonoma,Cabernet Franc,Red,2009,657.9,48.8,706.7,"1,935.6","$2,358.82","$4,565,800"
88,Sonoma,Cabernet Sauvignon,Red,2009,"11,658.5",730.5,"12,389.0","41,140.6","$2,280.67","$93,828,200"
89,Sonoma,Carignane,Red,2009,182.0,2.8,184.8,464.2,"$1,919.43","$891,000"
90,Sonoma,Malbec,Red,2009,281.8,82.1,363.9,877.9,"$2,491.49","$2,187,300"
91,Sonoma,Merlot,Red,2009,"5,736.9",109.1,"5,846.0","16,506.5","$1,507.00","$24,875,300"
92,Sonoma,Meunier,Red,2009,109.0,15.0,124.0,398.5,"$3,056.21","$1,217,900"
100,Sonoma,Other Reds,Red,2009,527.2,187.6,714.8,"1,839.7",$0.0,"$6,180,000"
93,Sonoma,Petite Sirah,Red,2009,503.9,85.9,589.8,"2,300.6","$2,480.13","$5,705,800"
94,Sonoma,Petite Verdot,Red,2009,189.0,34.8,223.8,918.9,"$2,778.24","$2,553,000"
95,Sonoma,Pinot Noir,Red,2009,"10,746.2","1,988.5","12,734.7","31,961.2","$3,043.08","$97,260,500"
96,Sonoma,Sangiovese,Red,2009,298.6,11.1,309.7,"1,210.6","$2,231.17","$2,701,100"
97,Sonoma,Syrah-Shiraz,Red,2009,"1,816.6",168.5,"1,985.1","5,563.3","$2,314.65","$12,877,100"
102,Sonoma,TOTAL ALL REDS,Red,2009,"37,937.2","3,636.2","41,573.4","120,717.0","$2,430.05","$293,348,400"
98,Sonoma,Zinfandel,Red,2009,"5,229.7",171.5,"5,401.2","15,637.4","$2,462.39","$38,505,400"
62,Sonoma,Cabernet Franc,Red,2010,653.9,14.3,668.2,"1,436.3","$2,166.55","$3,111,900"
64,Sonoma,Cabernet Sauvignon,Red,2010,"11,549.0",468.3,"12,017.3","37,933.3","$2,083.96","$79,051,500"
66,Sonoma,Carignane,Red,2010,180.3,1.0,181.3,270.4,"$1,949.11","$527,100"
68,Sonoma,Malbec,Red,2010,310.4,69.1,379.5,770.5,"$2,430.83","$1,873,000"
70,Sonoma,Merlot,Red,2010,"5,248.0",55.6,"5,303.6","17,440.9","$1,297.08","$22,622,300"
72,Sonoma,Meunier,Red,2010,108.5,15.0,123.5,406.5,"$2,928.56","$1,190,500"
99,Sonoma,Other Reds,Red,2010,466.6,48.0,514.6,"1,214.8",$0.0,"$9,416,500"
74,Sonoma,Petite Sirah,Red,2010,522.6,37.7,560.3,"2,085.9","$2,377.94","$4,960,200"
76,Sonoma,Petite Verdot,Red,2010,202.9,9.2,212.1,695.5,"$2,476.49","$1,722,400"
78,Sonoma,Pinot Noir,Red,2010,"11,456.0",675.5,"12,131.5","29,791.3","$2,825.12","$84,164,000"
80,Sonoma,Sangiovese,Red,2010,259.7,48.4,308.1,983.6,"$2,244.09","$2,207,300"
82,Sonoma,Syrah-Shiraz,Red,2010,"1,791.6",51.7,"1,843.3","4,587.6","$2,030.22","$9,313,900"
86,Sonoma,TOTAL ALL REDS,Red,2010,"37,337.9",1558.3,"38,896.1","108,497.4","$2,211.08","$239,896,431"
101,Sonoma,TOTAL ALL REDS,Red,2010,"37,804.4","1,606.3","39,410.7","108,481.0","$2,255.85","$244,717,100"
84,Sonoma,Zinfandel,Red,2010,"5,055.0",112.5,"5,167.5","10,864.4","$2,260.27","$24,556,500"
61,Sonoma,Cabernet Franc,Red,2011,655.9,6.7,662.6,"1,568.6","$2,209.15","$3,465,300"
63,Sonoma,Cabernet Sauvignon,Red,2011,"11,726.8",291.5,"12,018.3","33,126.8","$2,111.24","$69,938,700"
65,Sonoma,Carignane,Red,2011,615.4,0.0,615.4,373.2,"$2,019.14","$753,600"
67,Sonoma,Malbec,Red,2011,322.4,76.6,399.0,"1,110.5","$2,340.51","$2,599,200"
69,Sonoma,Merlot,Red,2011,"5,126.6",23.4,"5,149.9","14,670.5","$1,380.85","$20,257,800"
71,Sonoma,Meunier,Red,2011,108.5,15.0,123.5,301.4,"$2,698.80","$813,500"
73,Sonoma,Petite Sirah,Red,2011,575.0,22.2,597.1,"2,521.1","$2,325.25","$5,862,200"
75,Sonoma,Petite Verdot,Red,2011,209.2,2.6,211.8,851.7,"$2,461.02","$2,096,100"
77,Sonoma,Pinot Noir,Red,2011,"11,862.6",377.1,"12,239.7","28,350.2","$2,902.47","$82,285,700"
79,Sonoma,Sangiovese,Red,2011,89.5,36.5,126.0,845.2,"$2,204.51","$1,863,300"
81,Sonoma,Syrah-Shiraz,Red,2011,"1,773.1",19.1,"1,792.3","3,614.0","$2,124.31","$7,677,300"
85,Sonoma,TOTAL ALL REDS,Red,2011,"38,281.7",951.7,"39,233.4","101,818.5","$2,301.97","$234,383,132"
83,Sonoma,Zinfandel,Red,2011,"5,216.8",81.1,"5,297.9","13,101.0","$2,357.61","$30,887,100"
44,Sonoma,Cabernet Franc,Red,2013,604.5,13.2,617.7,"1,917.8","$2,445.23","$4,689,500"
45,Sonoma,Cabernet Sauvignon,Red,2013,"11,830.3","1,070.8","12,901.1","44,255.8","$2,462.99","$109,001,600"
46,Sonoma,Carignane,Red,2013,579.6,4.0,583.6,506.7,"$1,870.18","$947,700"
47,Sonoma,Malbec,Red,2013,425.7,109.4,535.1,"2,706.6","$2,356.19","$6,377,300"
48,Sonoma,Merlot,Red,2013,"4,619.9",27.3,"4,647.2","18,784.5","$1,607.03","$30,187,300"
50,Sonoma,Meunier,Red,2013,91.8,6.6,98.4,716.9,"$2,285.40","$1,638,500"
52,Sonoma,Petite Sirah,Red,2013,598.3,83.5,681.8,"2,856.8","$2,477.06","$7,076,500"
53,Sonoma,Petite Verdot,Red,2013,236.9,30.5,267.4,"1,120.0","$2,840.39","$3,181,300"
55,Sonoma,Pinot Noir,Red,2013,"12,539.3",948.1,"13,487.4","54,826.8","$3,079.99","$168,866,000"
57,Sonoma,Sangiovese,Red,2013,195.9,12.7,208.6,"1,141.1","$2,383.10","$2,719,400"
58,Sonoma,Syrah-Shiraz,Red,2013,"1,731.9",7.0,"1,738.9","4,835.8","$2,246.05","$10,861,500"
60,Sonoma,TOTAL ALL REDS,Red,2013,"39,788.7","3,167.3","42,956.0","156,435.3","$2,558.50","$400,239,800"
59,Sonoma,Zinfandel,Red,2013,"5,139.0",159.8,"5,298.8","20,172.3","$2,444.51","$49,311,400"
27,Sonoma,Cabernet Franc,Red,2014,571.8,15.8,587.6,"1,913.9","$2,669.35","$5,108,900"
29,Sonoma,Cabernet Sauvignon,Red,2014,"11,689.7","1,078.2","12,767.9","45,772.0","$2,614.37","$119,665,000"
31,Sonoma,Carignane,Red,2014,178.8,1.0,179.8,478.8,"$1,947.37","$932,500"
32,Sonoma,Grenache,Red,2014,119.3,5.2,124.5,701.7,"$2,830.53","$1,986,200"
33,Sonoma,Malbec,Red,2014,491.0,41.8,532.8,"2,688.9","$2,427.49","$6,527,300"
34,Sonoma,Merlot,Red,2014,"4,308.6",27.7,"4,336.2","16,989.6","$1,651.47","$28,057,900"

In [ ]:
sonoma_2017_sorted = sonoma_2017.sort_values(['Year', 'Varietal'])
sonoma_2017_sorted

## Indivdual Year Testing

In [ ]:
#2011 is urls[10]
#2010 is urls[11]
#2009 is urls[12]
#2008 is urls[13]
#2007 is urls[14]
#2006 is urls[15]
#2005 is urls[16]
#2004 is urls[17]
#2003 is urls[18]
#2002 is urls[19]
#2001 is urls[20]
#2000 is urls[21]



urls[6]

In [ ]:
# utilize camelot to read pdf file at page 12, capture precisely with stream and close up the row gap with row_tol = 10

tables = camelot.read_pdf(urls[6], pages='12', flavor='stream', row_tol=10)
data = tables[0].df
dat = tables[0].parsing_report
dat

In [ ]:
camelot.plot(tables[0], kind='contour').show()

In [ ]:
data

In [ ]:
# data.columns = ['0', '1', '2', '3', '4', '5', '6', '7']
# data

In [ ]:
# drop rows that is not helpful
data = data.drop([0,1], axis=0)
data
# for 2011 report, also drop an empty row

In [ ]:
# # For 2016 crop report:

# # temp is non-bearing
# data['Temp'] = data['3']  # Create a temporary column and store 'Bearing' values
# data['3'] = data['2']  # Move 'Non-Bearing' values to 'Bearing' column
# data['2'] = data['Temp']  # Move temporary values to 'Non-Bearing' column
# data.drop('Temp', axis=1, inplace=True)  # Drop the temporary column
# data

In [ ]:
# special for 2006, 2002; $ sign is in its separate column
# rename its column, add the dollar column with the value
# data.columns = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


# data['7'] = data['6'] + data['7']
# data['9'] = data['8'] + data['9']
# data = data.drop(['6', '8'], axis=1)
# data = data[:28]
# data

In [ ]:
# special for 2010; $ sign is in its separate column
# rename its column, add the dollar column with the value
# data.columns = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


# data['7'] = data['6'] + data['7']
# data['9'] = data['8'] + data['9']
# data = data.drop(['6', '8'], axis=1)
# data

In [ ]:
# rename my columns
new_columns = ['Varietal', 'Year', 'Bearing' , 'Non-Bearing', 'Total', 'Tons', '$/Ton', 'Total Value']
data = data.rename(columns=dict(zip(data.columns,new_columns)))
data

In [ ]:
data['Bearing'] = data['Bearing'].str.replace(' .', '.', regex=False)
data['Bearing'] = data['Bearing'].str.replace('--', '0.0', regex=False)
data['Non-Bearing'] = data['Non-Bearing'].str.replace(' .', '.', regex=False)
data['Non-Bearing'] = data['Non-Bearing'].str.replace('--', '0.0', regex=False)

data['Total'] = data['Total'].str.replace(' .', '.', regex=False)
data['Total'] = data['Total'].str.replace('--', '0.0', regex=False)
data['$/Ton'] = data['$/Ton'].str.replace(' .', '.', regex=False)
data['Total Value'] = data['Total Value'].str.replace(' ', ',')

In [ ]:
# data['Total'] = pd.to_numeric(data['Total'], errors='coerce')
# data

In [ ]:
data

In [ ]:
# data = data[:28]
# data

In [ ]:
# data.loc[28][0] = data.loc[29][0]
# data.loc[29][0] = ''

In [ ]:
data

In [ ]:

# specific fixes for 2004

# 28		2010	37,804.4	1,606.3	39,410.7	108,481.0\n(a	) $2,255.85 (a	) $244,717,100
# 29	TOTAL REDS	2009	37,937.2	3,636.2	41,573.4	120,717.0\n(a	) $2,430.05 (a	) $293,348,400	
			
# data.loc[28][0] = data.loc[29][0]
# data.loc[29][0] = ''

# # data drop empty row
# data = data.query("Year != '' and Total != '' and Tons != ''")
# data

# data drop empty row
# data = data[:28]
# data

In [ ]:
# data['Varietal'].unique()

In [ ]:
# data.loc[data['Varietal'].str.contains('Cabernet'), 'Varietal'] = 'Cabernet Sauvignon'
# data.loc[data['Varietal'].str.contains('Sangiovese/'), 'Varietal'] = 'Sangiovese/Sangioveto'

In [ ]:
# data['Varietal'].str.contains('Sangiovese/')

In [ ]:
data['Varietal'] = data['Varietal'].replace('Mataro/', 'Mataro/Mouvedere')
data['Varietal']= data['Varietal'].replace('Cabernet', 'Cabernet Sauvignon')

# for 2016 only 
data['Varietal'] = data['Varietal'].replace('Sangiovese/', 'Sangiovese')
# for 2016 Syrah - Shiraz to Syrah-Shiraz ; 
data['Varietal'] = data['Varietal'].replace('Syrah - Shiraz', 'Syrah-Shiraz')

# for 2005 only
data['Varietal'] = data['Varietal'].replace('Cabernet Sauv.', 'Cabernet Sauvignon')

data['Varietal']= data['Varietal'].replace(['', 'including other reds', 'Mouvedere', 'Mourvedere (a)', 'Sauvignon', 'Sangioveto'], np.nan)
data = data.reset_index(drop=True)

data['Varietal'].unique()

In [ ]:
data['Varietal'] = data['Varietal'].dropna().repeat(2).reset_index(drop=True)
data['County'] = 'Sonoma'

In [ ]:
first_column = data.pop('County')
data['Grape Color'] = 'Red'
third_column = data.pop('Grape Color')
data.insert(0, 'County', first_column)
data.insert(2, 'Grape Color', third_column)
data

In [ ]:
data['Tons'] 
data['$/Ton']
data['Total Value']

In [ ]:
# for 2004 only 

data['Bearing'] = data['Bearing'].str.replace(' ', '.')
data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
data['Total'] = data['Total'].str.replace(' ', '.')

# data['Tons'] = data['Tons'].str.replace(' ', '.')
# data['$/Ton'] = data['$/Ton'].str.replace(' ', '')
# data['Total Value'] = data['Total Value'].str.replace(' ', ',')

# # specific for 2004

# we could do .apply lambda function for all the possible combinations so we don't have to add specificly for each year

data['$/Ton'] = data['$/Ton'].str.replace(' \n', '', regex=False)
data['$/Ton'] = data['$/Ton'].str.replace(' ', '', regex=False)
data['Total Value'] = data['Total Value'].str.replace('  \n', '', regex=False)
data['Total Value'] = data['Total Value'].str.replace(' ', '', regex=False)
data['Total Value'] = data['Total Value'].apply(lambda x: '$' + x if '$' not in x else x)
data

In [ ]:
# # for 2007 only 

# data['Bearing'] = data['Bearing'].str.replace(' ', '.')
# data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
# data['Total'] = data['Total'].str.replace(' ', '.')

# # data['Tons'] = data['Tons'].str.replace(' ', '.')
# # data['$/Ton'] = data['$/Ton'].str.replace(' ', '')
# # data['Total Value'] = data['Total Value'].str.replace(' ', ',')

# # # specific for 2006


# # we could do .apply lambda function for all the possible combinations so we don't have to add specificly for each year

# data['Bearing'] = data['Bearing'].str.replace('*', '', regex=False)
# data['Total'] = data['Total'].str.replace('*', '', regex=False)
# data['$/Ton'] = data['$/Ton'].str.replace(' (a)', '', regex=False)
# data['Total Value'] = data['Total Value'].str.replace(' \n', '', regex=False)
# data['Total Value'] = data['Total Value'].str.replace(' ', '', regex=False)
# data['Total Value'] = data['Total Value'].apply(lambda x: '$' + x if '$' not in x else x)
# data

In [ ]:
# # for 2010, 2009, 2008 only 

# data['Bearing'] = data['Bearing'].str.replace(' ', '.')
# data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
# data['Total'] = data['Total'].str.replace(' ', '.')

# # data['Tons'] = data['Tons'].str.replace(' ', '.')
# # data['$/Ton'] = data['$/Ton'].str.replace(' ', '')
# # data['Total Value'] = data['Total Value'].str.replace(' ', ',')

# # # specific for 2010, 2009, 2008
# data['Tons'] = data['Tons'].str.replace('\n(a', '', regex=False)
# # data['$/Ton'] = data['$/Ton'].str.replace('', '0.0', regex=False)

# data['$/Ton'] = data['$/Ton'].str.replace(') ', '', regex=False)
# data['$/Ton'] = data['$/Ton'].str.replace(' (a', '', regex=False)
# data['$/Ton']  = data['$/Ton'].replace('', '$0.0', regex=False)
# data['Total Value'] = data['Total Value'].str.replace(') ', '', regex=False)

# data['Total Value'] = data['Total Value'].apply(lambda x: '$' + x if '$' not in x else x)
# data

In [ ]:
# data['$/Ton'].replace('', '$0.0', regex=False)

In [ ]:
# for 2011 only 

# data['Bearing'] = data['Bearing'].str.replace(' ', '.')
# data['Non-Bearing'] = data['Non-Bearing'].str.replace(' ', '.')
# data['Total'] = data['Total'].str.replace(' ', '.')
# data['Tons'] = data['Tons'].str.replace(' ', '.')
# data['$/Ton'] = data['$/Ton'].str.replace(' ', '')
# # data['Total Value'] = data['Total Value'].str.replace(' ', ',')

# # specific for 2011
# data['Tons'] = data['Tons'].str.replace('*', '', regex=False)
# data['$/Ton'] = data['$/Ton'].str.replace('*', '', regex=False)
# data['Total Value'] = data['Total Value'].str.replace('\n', '', regex=False)
# data['Total Value'] = data['Total Value'].str.replace('(a)  $ ', '$', regex=False)
# data['Total Value'] = data['Total Value'].str.replace('*', '', regex=False)

In [ ]:
data

In [ ]:
# for 2016 only 

# data['Bearing'].str.replace(' .', '.', regex=False)
# data['Bearing'].str.replace('--', '0.0', regex=False)
# data['Non-Bearing'].str.replace(' .', '.', regex=False)
# data['Non-Bearing'].str.replace('--', '0.0', regex=False)

# data['Total'].str.replace(' .', '.', regex=False)
# data['Total'].str.replace('--', '0.0', regex=False)
# data['$/Ton'].str.replace(' .', '.', regex=False)
# data['Total Value'].str.replace(' ', ',')

In [ ]:
len(data)

In [ ]:
data.to_csv('example.csv', index=False, encoding='utf-8')

In [ ]:
# data['Varietal'] = data['Varietal'].replace('', method='ffill')
# data